### ISSUE TITLE
Collect system statistics 

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#105]
As discussed, we want to collect several statistics about our system.
For now we'll want to collect statistics about the stack traces, how many traces we have, how many traces are for each exception type. 
Also we want to see how many traces are getting sorted using our distancer algorithms.

This info is important to measure perfomance, and we also need it for tomorrow for Adi.

**Comment by AmitOhayon** [comment]
Results:
Total number of exceptions - 4680
Most common exception - java.lang.NullPointerException, with 10598 instances
Number of exceptions with at least 5 instances - 936
Average stack trace length - 1382.929 characters, max length - 31888
`SELECT * FROM bugquery_index3 WHERE ex=java.lang.NullPointerException` query duration - 1.077 seconds

Histogram will be added by @tonylekhtman soon

**Comment by tonylekhtman** [comment]
![image](https://cloud.githubusercontent.com/assets/7457420/25784040/54d449de-336f-11e7-9569-710eff2e4b67.png)

**Comment by AmitOhayon** [comment]
We did noticed some malformed exception extractions such as \`java.lang.NullPointerException\`, \[java.lang.NullPointerException etc.. But this issue is probably not of high priority atm anyway

**Comment by yonzarecki** [comment]
In our meeting with Adi, Yossi suggested that in order to measure performance in our graph, we need to take into account that the more common exception type also gets queried more often. 
So in our average calculation, we need to calculate it on our histogram graph ^ 2 (more traces = more queries), and this is how we'll get the correct average runtime.
