### ISSUE TITLE
Obtain a server with a public ip from the faculty

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#106]
We need to get the server from the faculty, install our system on it and start using it.
We started working on it and talked to nadav toledo, but we need to prussure him and see it through.

**Comment by yonzarecki** [comment]
@AmitOhayon updated that we'll have to wait until a meeting on Thursday on the subject.
So no probably no updates until then :(

**Comment by yonzarecki** [comment]
Update from Amit, Nadav sent us an email saying he has a solution he'll talk to us next week :D
Probably won't happen until Monday tho.

**Comment by yonzarecki** [comment]
@AmitOhayon, I know that you are on vacation, but can you send me the email conversation with Nadav ? This issue is pretty high-priority and maybe I can talk to Nadav and see whats going on.

**Comment by ZivIzhar** [comment]
Done. Please look at the telegram group, I wrote a long message regarding the server.
