### ISSUE TITLE
Write presentation for customer meeting

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#109]
Present to the customer our plans for the future and ask him for his opinion.

**Comment by yonzarecki** [comment]
@yosefraisman Can you a link to the presentation here

**Comment by yosefraisman** [comment]
@yonzarecki [link](https://docs.google.com/presentation/d/1hSYLo6pDKFytTNpAjcGAIiCquZ5qknfyqNFgHNdUFbc/edit?usp=sharing)
