### ISSUE TITLE
Add text based db index

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#111]
Currently the longest db access time is ~1 sec.
However, Adi still thinks this is too long, and can be decreased to 0.01 when a text-based db index is used.

In this issue we'll add and the text-based index to our db system.

**Comment by tonylekhtman** [comment]
I think this [http://docs.doctrine-project.org/en/latest/reference/annotations-reference.html#annref-index](url) can help us with adding index to the orm.

**Comment by tonylekhtman** [comment]
@AmitOhayon

**Comment by yonzarecki** [comment]
Do we really need an index for performance ? The DB isn't as slow as we initially thought

**Comment by tonylekhtman** [comment]
I guess we need to check this first on different kinds of searches (popular and unpopular exceptions)

**Comment by tonylekhtman** [comment]
After a chcek, apparently this link wasn't what we were looking for.
It seems not so important as @yonzarecki  said because our fetch time decreased since we moved to the new server.
Closing for now because it has low priority in my opinion.
