### ISSUE TITLE
Implementing Plug-in Marker Help

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#112]
As discussed in our customer meeting, we decided to implement the marker approach which shows in which lines the exception happened and suggests to go to the BugQuery website and fix it.

We also discussed how a "?" marker will be more suiting than the "X" marker Doron showed in his demo.

Another cool option is to add buttons in the marker menu to go up and down the trace, moving the user to the upper/lower line in the stack-trace

This issue is related to #78 (I think) and will be continued when it will be closed.

**Comment by mdoron** [comment]
After playing a with all these classes and extension points, I'm starting to think it's maybe a good idea to create our own editor. I will look deeply into [it](http://www.eclipse.org/eclipse/platform-text/eclipseCon/talk.pdf) this week.

**Comment by mdoron** [comment]
The main of the system is built so this issue can be closed.
