### ISSUE TITLE
Extending the Stacktrace Console

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#114]
Adding a small "reflex" button to the eclipse console, can enable an easier access to BugQuery when an exception happens.
The result should be like in the customer presentation's last slide.

**Comment by yosefraisman** [comment]
![It's Alive!](https://cloud.githubusercontent.com/assets/16455692/25998140/3c276710-3728-11e7-8379-a5ed88989b72.png)
