### ISSUE TITLE
Data Intuition - Look at our data

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#115]
As suggested by Yossi, this is a good time to start looking at our stack-traces data, and look for hints within it. 
Can we see some similarity between traces that we can translate into better performing algorithms ?

We should add prints and sample instances from the db and see if we can realize something important from looking at our data.

**Comment by yonzarecki** [comment]
Moving to Sprint 2, as this issue is not critical to our commitments for Sprint 1.

**Comment by yonzarecki** [comment]
@tonylekhtman  Can you help me get started ? Where do I need to go if i just wanna send some SQL queries and look at the results ?

**Comment by tonylekhtman** [comment]
The best way in my opinion is via mysql workbench. It presents the results in a nice tabular form.
You can also send queries via the teminal. You need to write mysql -u <local database user name> -h <database server ip address> -p

**Comment by yonzarecki** [comment]
I got it working, looking d:

**Comment by yonzarecki** [comment]
From looking at the questions I can see that most exceptions are under a <code> tags,  this can help with exception detection and extractions.

**Comment by yonzarecki** [comment]
There is also many duplicates in the DB (this may result in duplicate results in query time)

**Comment by yonzarecki** [comment]
Another idea is to keep an index of all rows seen, and give lower significance to those rows in the distance functions.

**Comment by yonzarecki** [comment]
I suppose this is already implemented, but most newlines in the DB are represented by "&#xA;", if it doesn't it can help with  exception parsing.

**Comment by yonzarecki** [comment]
We should look more into the exception trace print types. There are several of them, yet they all represent the same thing. A few examples are 268 vs. 261 vs. 262 etc.

A good idea is maybe to analyse these types better and make a "generic" print for us to compare, this way we won't miss a good answer because of different printing styles.

**Comment by yonzarecki** [comment]
I think I'm done for now, this gave us enough work for the time being.
I'll open issues about these topics tomorrow.
