### ISSUE TITLE
Explore adding cache to the DB

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#116]
In this issue we'll explore how to add caching capabilities to the database, we'll write our research results here and open a new issue for implementation.

**Comment by tonylekhtman** [comment]
Might be helpful [link](https://dev.mysql.com/doc/refman/5.7/en/query-cache.html)

**Comment by tonylekhtman** [comment]
[Anther important link](https://dev.mysql.com/doc/refman/5.7/en/query-cache-configuration.html)

**Comment by tonylekhtman** [comment]
Enabled cache, it was done through the settings of the mysql server.
The settings i set are:
query_cache_type = 1(must)
query_cache_size = 16M (can be modified due to requirements).

If someone wants to change the size setting they can contact me.
