### ISSUE TITLE
Decide which to use: CodeCov or JaCoCo

### ISSUE THREAD

**Issue by ZivIzhar** [TechnionYP5777/Bugquery#119]
CodeCov - a code coverage platform that is being ran by Travis CI every commit.
JaCoCo - a java code coverage library - we need to run it "manually"

Right now, CodeCov is only able to run one of our "sub projects" and cant ignore any files/classes.
JaCoCo can (probably from what I read) run both projects and ignore files/classes/etc.

So, as I wrote in #103, we should decide whether we stick to the limited CodeCov which is being ran by Travis.
Or use JaCoCo - which we'll need to run manually.

**Comment by mdoron** [comment]
Theoretically it would be better for our coverage report if we use JaCoCo (if I understood correctly).
@ZivIzhar What is our percentage right now with the regular CodeCov?

**Comment by ZivIzhar** [comment]
Our CodeCov coverage rate is 47% while including uncovered code that shouldn't be included

**Comment by AmitOhayon** [comment]
Why do you think converting our project to a project with submodules is difficult? I remember doing it myself last semester

**Comment by ZivIzhar** [comment]
Not to sub modules
From submodules to no submodules

Problematic because of the files transfers

**Comment by AmitOhayon** [comment]
I'm not sure I understand - aren't you talking about changing the flat model to one with hierarchy?

**Comment by ZivIzhar** [comment]
After searching the internet for a while, I'm not sure that a hierarchy model would work... might be worth a shot, but will cause everyone to deal with merges (maybe twice since it might not work)
I think that codecov just cant handle multi module projects so well...

**Comment by yonzarecki** [comment]
We can try opening a dummy project and changing the hierarchy there.
Also, the main issue here is the hierarchy of the modules or that CodeCov can't ignore files ?

**Comment by yonzarecki** [comment]
@ZivIzhar updated me that we can run JaCoCo inside travis as an add-on, providing the best of both worlds.
We will update our code coverage tool in the near future.
