### ISSUE TITLE
Get Trace from Console

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#12]
Implement the initial plugin use-case: a program has ran, click our button (or select the proper option in the menu, or click `ctrl+6`) to get the stack trace from the output console. For more insight into initial ideas re plugin design, visit [BugQuery: Plugin Options](../wiki/Plug-in-Development,-Initial-Research) in our Wiki.
### Progress
- [x] Extract output from consoles (pick the relevant one)
- [x]  Menu item, Button, Keyboard shortcut 
- [x] Parse output to get the stack trace exclusively (disregard other output)

**Comment by yossigil** [comment]
milestone? label?

**Comment by yosefraisman** [comment]
@yossigil added a milestone. We'll sort out the rest of the confusion re milestones at our meeting tomorrow with @AdiOmari . Thanks!
