### ISSUE TITLE
Extract files and line numbers from eclipse's stack trace

### ISSUE THREAD

**Issue by mdoron** [TechnionYP5777/Bugquery#120]
As we spoke

**Comment by mdoron** [comment]
@yosefraisman you did well.
Notice that we also need the package name and the project.
I researched about hyperlinks in the console (I think you did it too) and reached the conclusion it's better to just parse it all then to get entangled with this... 
In the stack trace you don't get the project name so I'll look for a way to get it.

**Comment by mdoron** [comment]
@yosefraisman what's going on with the package names? Do you want me to do it instead?

**Comment by yosefraisman** [comment]
Go for it! You can also close this issue, as we successfully extracted the files and line numbers from the stack trace (maybe add a new one for extracting packages).
