### ISSUE TITLE
Find the current project name

### ISSUE THREAD

**Issue by mdoron** [TechnionYP5777/Bugquery#121]
Since we can't get it from the stack trace and we need it in order to put our markers in it

**Comment by mdoron** [comment]
Update: apparently it's harder than it seems.

**Comment by mdoron** [comment]
Update: As Greg [suggested](https://stackoverflow.com/questions/44075195/get-file-path-from-ihyperlink#), this lead would be investigated.

**Comment by yosefraisman** [comment]
We already have methods of picking up the trace (so we don't need `org.eclipse.ui.console.consolePatternMatchListeners`). We just need a way to search for the file (using Eclipse JDT Search Engine as was suggested), right?

**Comment by mdoron** [comment]
I think you're right, I'm assigning you too to this issue

**Comment by mdoron** [comment]
It's too complicated for now - I have a solution that will work. We will look for all the open projects and let the user mark the project he wants us to work on.  This is not perfect solution but this will work.

FYI: @yosefraisman 

@AdiOmari do you approve? We have a serious problem in finding the last launched project name, and I think this will solve the problem.

**Comment by yosefraisman** [comment]
Sounds reasonable.
