### ISSUE TITLE
Add BugQuery to eclipse marketplace

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#123]
Following #107, we will now add BugQuery to the eclipse marketplace. This issue is currently on-hold #106 as a server is needed for this process.

**Comment by yonzarecki** [comment]
As we (finally) received a working server, we can start working on this issue.

**Comment by yosefraisman** [comment]
### Progress
- [x] marketplace account
- [x] feature project
- [ ] #137 & add deployment files to server (easy)
- [ ] add to marketplace
