### ISSUE TITLE
Thinking group: does our markers should be persistent or non-persistent?

### ISSUE THREAD

**Issue by mdoron** [TechnionYP5777/Bugquery#125]
We have the option the markers would stay if we close the eclipse or not - what is it we prefer?

**Comment by yonzarecki** [comment]
Lets talk about it in our meeting this week, shall we ?

**Comment by yosefraisman** [comment]
I think when we close Eclipse the markers should disappear. Maybe even when the console they were created from is closed (this shouldn't be hard to implement as I already have a button in that stack).

**Comment by mdoron** [comment]
OK so for now it's not persistent (#126) and in every time we send the trace we remove all of our markers, which make sense. @yosefraisman open an issue about the part you mentioned and I'll see what I can do.

I think this is all for now
