### ISSUE TITLE
Implementing basic Google crawling capabilities for our website

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#127]
Following #113, in this issue we will implement some basic crawling capabilities for Google's crawler.
Many more advanced capabilities will probably require help from the DB team, but for now we'll implement only basic stuff, such as:
 - [x] Install Google analytics.
 - [x] Add some static pages to the website for Google to crawl #129 
 - [x] create a sitemap and upload it to Google Webmaster Tools (as discussed in #113).
 - [x] Submit our URL to Google
 - [x] Putting links to our website in social media.
 - [x] Add title tags with descriptive title to each static html page
 - [x] Add description meta tags with short description to each static html page

**Comment by rodedzats** [comment]
Closed with @ZivIzhar
