### ISSUE TITLE
Get Trace From User Input

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#13]
Expand use cases for stack trace obtaining. This issue is for getting the stack trace directly from the user. (parse input using `class ExtractTrace` from #12).
### Possible Use Cases, Progress
- [x] Get trace using `getSystemClipboard()` (see [link](https://docs.oracle.com/javase/7/docs/api/java/awt/Toolkit.html#getSystemClipboard()))
- [x] Get trace from a special input window
- [ ] Fix bug with clipboard implementation. When copying content that originates in eclipse, using "Trace from Clipboard", clipboard access fails (`!content.isDataFlavorSupported(DataFlavor.stringFlavor)`, happens - only in Linux).

**Comment by yosefraisman** [comment]
Progress: There's a working implementation of trace extraction from clipboard (needs cleanup, and there's a bug - `getSystemClipboard()` doesn't seem to work properly with content from within eclipse). Also, I know what to do about the input window (create a subclass of `org.eclipse.jface.dialogs.InputDialog`)

**Comment by yossigil** [comment]
Suggestion: write a test class to demonstrate what's working.

**Comment by yosefraisman** [comment]
Finished `class ExtendedDialog` and `class FromInputDialog`. Adding a test class isn't worth the time, I think, since it's impossible to cover user behavior when we offer interaction devices we can't emulate correctly (for example, the system clipboard toolkit access, which - it seems - has a bug in Linux we couldn't detect with a test class).
However, here's [a video](https://youtu.be/nFCnRwJ2IaQ) I made demonstrating all the input methods our plug-in supports so far (temporarily switching `class SendTrace`'s default behavior to showing the output in a window, instead of searching Google for it).

**Comment by yossigil** [comment]
You cannot run the video to make sure the class still works

**Comment by yosefraisman** [comment]
That's true, but it's good for demonstration (as you requested). I'm looking into testing the methods and interaction that can be covered.

**Comment by yossigil** [comment]
:+1:

**Comment by yosefraisman** [comment]
As discussed in our meeting, initial implementation of trace extraction from user input is complete. This week I'll deal with the two remaining problems with the current implementation (One is the clipboard bug in Linux, the second is the redrawing of the drop-down menu after clicking OK in the InputDialog). I'll add the new issues soon. Additionally, I'll add an issue for testing the methods from GetTrace, as requested in this thread.

**Comment by yossigil** [comment]
:+1:
