### ISSUE TITLE
Set-up review meetings with Yossi

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#130]
We need to set up review meeting with Yossi this week.
You can book him in [here][1]

Add V for yourself after you've set up a meeting : 
- [x] Yonatan
- [x] Ziv
- [x] Roded
- [x] Yosef
- [x] Amit
- [x] Tony
- [x] Doron - Wednesday 13:30

  [1]: https://yogi.youcanbook.me/index.jsp

**Comment by yonzarecki** [comment]
@AmitOhayon @tonylekhtman Did you set-up a meeting already ?

**Comment by AmitOhayon** [comment]
Yes, on Wednesday

**Comment by tonylekhtman** [comment]
Yes, on wed

**Comment by yonzarecki** [comment]
Great, closing issue.
