### ISSUE TITLE
Create a view that shows all of our markers

### ISSUE THREAD

**Issue by mdoron** [TechnionYP5777/Bugquery#131]
I want us to have a view in which it would be possible to see all of our markers

**Comment by yosefraisman** [comment]
I really like this idea! @mdoron

**Comment by mdoron** [comment]
This can actually be in sprint 2 since we did not commit to the client we'll do it, but I'll start working on this week hopefully finishing it before the end of the sprint

**Comment by mdoron** [comment]
I've noticed that the "Marker view" already implementing large part of what we want, maybe it's enough. I'm gonna check it out today.

**Comment by mdoron** [comment]
Our markers can be viewed in the "Marker view", hence this issue is unnecessary.
