### ISSUE TITLE
Setting up DB on Faculty server

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#133]
As received our server in #106, we can now move our SQL server to the new server.

**Comment by yonzarecki** [comment]
Currently Tony is building the DB on Adi's server, and after this is finished he will move it to the faculty server.

**Comment by tonylekhtman** [comment]
Adi's sql server stopped answering queries  for some reason.
I'll set it up on the new server and continue with adding answers directly to it.

**Comment by tonylekhtman** [comment]
The original db is now on the new server and can be accessed through tunnel.
What is left is #134.

**Comment by tonylekhtman** [comment]
Finished setting up db. DB contains now both questions and selected answers.
