### ISSUE TITLE
Run Website on ssdl-bugquery (:80)

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#137]
Running the sprint-boot app on our new server. This is a requirement for issue #123.
- [x] Figure out how to run the website in the new server, in port 80.
- [x] Implement.
- [x] Make the port available outside the network of the Technion. @yonzarecki has taken this under his responsibility.

**Comment by yosefraisman** [comment]
Look at [Deploying Spring Boot applications](https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html) in the Sprint Boot docs.

**Comment by yonzarecki** [comment]
Just saying, this issue is also related to #123, as running the server on port 80 is crucial for adding the plugin to the marketplace.

**Comment by yonzarecki** [comment]
Nadav updated me that the port will be open pretty soon, will update here.

**Comment by yosefraisman** [comment]
@yonilx any news? maybe we should bug him again

**Comment by yonzarecki** [comment]
No updates ):
It will probably take some time since the technion is closed now.
I'll send him a "what's up" mail.

**Comment by yonzarecki** [comment]
I've run the server on my own server's address. It is open in yonilx.ddns.net:2017
