### ISSUE TITLE
Explore adding quick answers on markers

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#138]
A major enhancement to the plugin's markers is to add quick suggestion from the server to the user.

In this issue we will explore what we will need to implement such feature (from the server or any other part of the system).

**Comment by mdoron** [comment]
yes, the idea is that even if we cannot give a summary of the answer, we can still say something like - 
"XXXException: BugQuery advices you to check this link"

Or even implement it as some sort of quickfix

**Comment by mdoron** [comment]
@AmitOhayon , I'm assigning you as the representative of the server side. We will think about this together. If you want someone else to deal this issue with me, assign him instead/additionaly.

**Comment by yonzarecki** [comment]
We discussed adding a page that returns the results as JSON instead of a full HTML.
This way it will be easier to parse in the plugin.

**Comment by yonzarecki** [comment]
I think Adi's opinion is clear in this matter, as we DON'T want the client to remain in eclipse and send him\her to the website whenever possible.

**Comment by mdoron** [comment]
Still, we do need to decide what is going to be written on the markers, and we decided a quickfix mechanism will be implemented, which will direct the user to the website.
