### ISSUE TITLE
Build regular expression

### ISSUE THREAD

**Issue by rodedzats** [TechnionYP5777/Bugquery#14]
We need to extract stack traces from stackoverflow questions. In order to recognize the stack-traces we need a regular expression string that matches all possible stack traces in that question.

**Comment by rodedzats** [comment]
Created a class for extracting stack traces, tested it on the following page (question and best answer):
http://stackoverflow.com/questions/3988788/what-is-a-stack-trace-and-how-can-i-use-it-to-debug-my-application-errors
The implementation is based on the initial work of @yosefraisman

**Comment by yossigil** [comment]
Can you please make a list of all issues that you closed, and issues you are still working on.

**Comment by rodedzats** [comment]
@yossigil I've closed #14 . I'm working on #8 and #20 with @yonzarecki like we discussed in our last weekly meeting.

**Comment by yossigil** [comment]
:+1: but this should be in your personal page.... Sorry for making the comment here. Feel free to erase this mistake and move to your todos page.
