### ISSUE TITLE
Add Answers

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#140]
Displaying answers from the new database. This requires adding a query for answers to the application, and changing `result.html` accordingly.

**Comment by tonylekhtman** [comment]
You don't need a new query. 
The answer is contained in the post object

**Comment by tonylekhtman** [comment]
When there is no selected answer, there is a null.

**Comment by yonzarecki** [comment]
Any updates ?

**Comment by yosefraisman** [comment]
All the hard work was done by Tony and Amit. I have a local copy with
answers, waiting for a different issue to push (also update the version on
the server)
