### ISSUE TITLE
Making the "Choose project" button do something

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#143]
Currently this button does nothing, a good use for it is to explain what the arrow (next to it) does, somewhat similar to long press in android. 
After clicking the button it will say something close to "please select a project from the arrow".

**Comment by mdoron** [comment]
I think that we gonna loose all of the buttons and make it a menu item. Much cleaner. Maybe we'll add a shortcut if needed. I will open another issue and close this later

**Comment by mdoron** [comment]
#154
