### ISSUE TITLE
Build a large trace example, showing the capabilities of our product

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#146]
Will help us at the presentation at the end of the semester.

**Comment by yonzarecki** [comment]
@yosefraisman Can you email me the puzzle example you presented at the start of the semester ?

**Comment by yosefraisman** [comment]
[Final version (I think)](https://www.dropbox.com/sh/zs8xa1nm5bvvka1/AADEslU7hViBdj3FaB7yq3mKa) @yonzarecki

**Comment by yonzarecki** [comment]
OK found a cool bug that can solved with BugQuery.
I've built a tutorial in 
https://github.com/TechnionYP5777/Bugquery/wiki/Use-case-Walkthrough:-Solving-a-bug-with-BugQuery

**Comment by yonzarecki** [comment]
Uploading the complete example here, it is linked in the tutorial.

[Yogi_Puzzle.zip](https://github.com/TechnionYP5777/Bugquery/files/1116990/Yogi_Puzzle.zip)

The guide is now complete
