### ISSUE TITLE
Explore options of keeping the user within eclipse when using the product

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#147]
Currently after every button press the client is shipped to the browser. 
We want to explore options of keeping him in eclipse, such a quick answers on markers (#138) and opening a browser window within eclipse, etc.

**Comment by mdoron** [comment]
My comment in #143 holds here too. I think the a BugQuery menu with option "Open BugQuery in browser" and maybe a shortcut would be great.

**Comment by yonzarecki** [comment]
Adi's opinion is clear in this matter, we DON'T want the client to remain in eclipse and send him\her to the website whenever possible.
This is contradictory to Tanya's opinion, but Adi is the client and we will go by his say.
