### ISSUE TITLE
Replace "orig question" with question title in results page

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#148]
As suggested to us in the client game, we want to add instead of the "original answer" in the results page the original question string from the SO post.
This will make it clearer what the question was originally about.

**Comment by AmitOhayon** [comment]
@yonzarecki Could you elaborate? I do not remember this suggestion

**Comment by yonzarecki** [comment]
Tanya suggested it will be more clear to replace in the results page, the title for each result found instead of "result" or "original question" to the title of the question from SO.
This way the user will know what the question was about without reading the whole question.

**Comment by AmitOhayon** [comment]
Summoning @tonylekhtman as this means adding title field to our db 😢

**Comment by tonylekhtman** [comment]
Finished adding title in #161.
We can now it to the website.

**Comment by tonylekhtman** [comment]
It seems @yosefraisman finished adding this to the website as well.
