### ISSUE TITLE
Server Access & Tunnel Access

### ISSUE THREAD

**Issue by ZivIzhar** [TechnionYP5777/Bugquery#15]
Get access to the server via the faculty tunnels system (in order to access the server from outside the faculty) .

**Comment by yossigil** [comment]
@zvili DO not use lables for milestones. Please define a milestone, and a date for it.

@yh-github @AdiOmari

**Comment by tonylekhtman** [comment]
Any news about the server?

**Comment by AdiOmari** [comment]
@ZivIzhar @tonylekhtman It is being dealt with. Please proceed with other
stuff. No server related excuses will be accepted for lack of advancement.
As I said, assume you have the database (manually insert two or three
questions), and write the rest of the stuff.

**Comment by tonylekhtman** [comment]
Do you mean we should now be working on the website?
As of this week's protocol,[Third Meeting](https://docs.google.com/document/d/1PdNsOl42kTN8iYueHWbQZJ2HH35STFSCifor8GFowtc/edit?usp=sharing) all of our issues are server related.

**Comment by ZivIzhar** [comment]
Closing this issue, this is a duplicate of #22 .
