### ISSUE TITLE
Fix - Server crashes if there are fewer than 10 results

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#156]
Currently the server crashes if there are fewer than 10 results, in this issue we will fix this bug.

**Comment by AmitOhayon** [comment]
I think the issue is deeper than this. The question we should ask ourselves is how many results do we want to display? Do we always limit the maximal amount to 10?

**Comment by yonzarecki** [comment]
Yes, you are right.
But ATM we should still fix this particular bug.

**Comment by tonylekhtman** [comment]
I think I fixed it what is the example you used for which it crashed?
Just to verify.

**Comment by yonzarecki** [comment]
Maybe just find a non popular exception type from the histogram you made and make up a small trace with it

**Comment by tonylekhtman** [comment]
Checked with a real stack trace that previously failed from [here](https://stackoverflow.com/questions/11282599/setup-oracle-11g-in-integration-of-jsf-spring-hibernate)(the first one)
Currently works, If there are problems with more stack traces, please reopen.
