### ISSUE TITLE
Design loading page

### ISSUE THREAD

**Issue by AmitOhayon** [TechnionYP5777/Bugquery#157]
Design the newly added loading page (resources/templates/loading).
@yosefraisman, would you kindly? :pray: 
Milestone is Sprint II atm, but shouldn't be too much work.

**Comment by yosefraisman** [comment]
![OK](https://user-images.githubusercontent.com/16455692/26905490-53fe49bc-4bf0-11e7-933c-d723a7013ccf.gif)
