### ISSUE TITLE
Settting up the project environment for MySQL

### ISSUE THREAD

**Issue by tonylekhtman** [TechnionYP5777/Bugquery#16]
Set the java project to work with the jdbc and mysql libraries.

**Comment by ZivIzhar** [comment]
Example code for using jdbc:
https://www.mkyong.com/spring/maven-spring-jdbc-example/
spring-jdbc's documentation:
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/jdbc.html

**Comment by yossigil** [comment]
What the difference between #9 and this one? 

They seem identical. Try to defined a delirvrable.
@zvili @idabran

**Comment by tonylekhtman** [comment]
Done.
