### ISSUE TITLE
Set-up an easier import procedure for a new DB from StackOverflow

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#165]
Will be important for importing DBs in further years.

**Comment by tonylekhtman** [comment]
I'll be glad to get help in this issue from @ZivIzhar , since he worked on something similar in the past.

**Comment by yonzarecki** [comment]
If you guys think this is too much time we can probably pass

**Comment by tonylekhtman** [comment]
Closed
