### ISSUE TITLE
Update our developer installation tutorial

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#166]
It is currently out of date.
https://github.com/TechnionYP5777/Bugquery/wiki/Developer-Guide

**Comment by yonzarecki** [comment]
We also need to add some explanation about using passwords

**Comment by yonzarecki** [comment]
Also add screenshots, etc.

**Comment by AmitOhayon** [comment]
Need to add - in order to create the DB from a file, the user needs to consider [this](https://stackoverflow.com/questions/32737478/how-should-i-tackle-secure-file-priv-in-mysql); either copy the file to the mentioned directory or disable the flag

**Comment by yosefraisman** [comment]
Want to help out with the database part of the guide (open Developer Guide: Database)? I know basically nothing about it @AmitOhayon

**Comment by AmitOhayon** [comment]
note to self - write about enabling spring.jpa.hibernate.ddl-auto=create on first run

**Comment by yosefraisman** [comment]
Done.
