### ISSUE TITLE
Add a row with a link to the website below the exception trace (in eclipse)

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#168]
As Adi said, this is another way for the client to use the plugin and get to the site.

**Comment by mdoron** [comment]
The problem is not sending the user to the website, but building the feature that invoke this method. Hence, your comment about how hard this issue is, is not relevant.

**Comment by yonzarecki** [comment]
I'm just repeating what was said in the meeting, where Yosef said he has something for this, but OK.

**Comment by mdoron** [comment]
I added this quickfix, not finished yet but there is something -it's not possible to have a bugquery icon and a quickfix simultaneously so we have to choose.
