### ISSUE TITLE
Creating JSP pages for posting stack traces and displaying results

### ISSUE THREAD

**Issue by AmitOhayon** [TechnionYP5777/Bugquery#17]
Build a Jersey web application for posting stack traces from plugin.

- [x] install tomcat on local machine
- [x] create simple hello page
- [x] create page for posting stack trace
- [x] display the stack trace
- [x] edit above page so it uses distance algorithm stub
- [x] merge with Yosef's HTML views (#24)

**Comment by AmitOhayon** [comment]
[x] installed tomcat on local machine
![screenshot from 2016-12-07 18-13-46](https://cloud.githubusercontent.com/assets/1254412/20975747/0f93910a-bca9-11e6-82a1-4c7ef0a2d040.png)

**Comment by yossigil** [comment]
:+1:

**Comment by AmitOhayon** [comment]
after a long fight with tomcat, ubuntu & eclipse, [this](https://marcin-chwedczuk.github.io/using-tomcat-8.5-with-eclipse-neon) is the tutorial that solved my problems.
Not sure how smooth pulling it from git is gonna be, but on my machine it works without errors/warnings.

**Comment by yossigil** [comment]
No one can beat a determined Technion brilliant student. No one! Good job @AmitOhayon

**Comment by AdiOmari** [comment]
Good job Amit 👍
