### ISSUE TITLE
AnswerAdder and TitleAdder runs at every run of the website

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#173]
These run every time because they are defined as Components.
We should fix that.

![image](https://user-images.githubusercontent.com/23148393/27252377-9be0e20e-5365-11e7-8f0a-3b9016d14a55.png)

**Comment by tonylekhtman** [comment]
I'll check this out. TitleAdder is actually one time use and was only created because we didn't have titles at first. AnswerAdder should be used only after new import.

**Comment by yonzarecki** [comment]
Finished ?

**Comment by AmitOhayon** [comment]
It relates to #165, I think we can close this one and pick it up from there.
