### ISSUE TITLE
Set up someone to install and use our product as a client

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#177]
For the "reality test"

**Comment by yonzarecki** [comment]
Any updates ?

**Comment by mdoron** [comment]
I asked @koralchapnik and she asked me to remind her in the weekend

**Comment by yonzarecki** [comment]
She should be able to find them herself from the wiki. This is the whole point

**Comment by rodedzats** [comment]
Made this with @tomerdragucki , and tried a simple bug in a project. All went good.
