### ISSUE TITLE
Meeting Minutes

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#18]
I take responsibility for taking notes during our weekly team meetings, and maintaining them in [our Wiki](../wiki) and on [Google Docs](https://drive.google.com/drive/folders/0B025itSw4Y1SaDhwUzc2amt0WDA).
### Winter
- [x] [First Meeting](https://docs.google.com/document/d/1wyavY5-HFG75nDMn1EHbd8jLaNJbZyqliLq9JLw0aII/edit?usp=sharing), 23.11.16; General Notes, Work Plan, Weekly Goals
- [x] [Second Meeting](https://docs.google.com/document/d/182z5CihcGgIvf9_dbrosA8yvkO3-ymZcsVn3ld_4ugY/edit?usp=sharing), 29.11.16; Team Updates, New Weekly Goals
- [x] [Third Meeting](https://docs.google.com/document/d/1PdNsOl42kTN8iYueHWbQZJ2HH35STFSCifor8GFowtc/edit?usp=sharing), 6.12.16; Weekly Updates, Goals For Sprint I (Next Week)
- [x] [4th Meeting](
https://docs.google.com/document/d/1goKYhJto3HvRsYinj21ygbbvgLcAJ7uM-_5SgMo0hLc/edit?usp=sharing), 13.12.16; Weekly Updates, Server Talk, New Weekly Goals
- [x] [5th Meeting](https://docs.google.com/document/d/1pPCdrpbIOWzavyGII1kIfUGPsCT1_-yt5C5k_sfnvSQ/edit?usp=sharing), 20.12.16; Weekly Update, Prototype Discussion, Goals for Next Week
- [x] [6th Meeting](https://docs.google.com/document/d/1o4ZJI-iUOTtgg5KPWAYwiHGOHTUYwlfDHHUoB_1tpHo/edit?usp=sharing), 3.1.17; Weekly Updates (Future Goals), Plans for Next Week
- [x] [7th Meeting](https://docs.google.com/document/d/1nbpzaino71sSirvVD3Fm9aPdOkhhffwlvMAghnqZYhQ/edit?usp=sharing), 25.1.17; Server Talk, Next Semester, BugQuery as a Product
### Spring
- [x] [1st Meeting](https://docs.google.com/document/d/1AG4_60njp20o_0WeJ0z9-QDd81Gd6MRZrIm2QDBaTn8/edit?usp=sharing), 20.03.17; Goals for the Semester, New Features
 - [x] [2nd Meeting](https://docs.google.com/document/d/1sUGAdYhdsCWs_2iYTG4UazXb42jzdYcD90ucIr_WKA0/edit?usp=sharing), 2.4.17; Weeks 1-2, Plans for This Week

**Comment by yosefraisman** [comment]
Added this week's meeting, with @AmitOhayon's help.

**Comment by yossigil** [comment]
The pro name is "minutes" as in "minutes of May 35th meeting", or "2016-05-35: Minutes", or "Meeting 3: minutes", or better yet "Meeting 3: Action Items".

**Comment by yosefraisman** [comment]
Added today's meeting.

**Comment by yosefraisman** [comment]
Added today's meeting.

**Comment by yossigil** [comment]
Greate job Yosef.
@AdiOmari

**Comment by yosefraisman** [comment]
Added today's meeting.

**Comment by yosefraisman** [comment]
Added yesterday's meeting.

**Comment by yossigil** [comment]
:+1:
