### ISSUE TITLE
Exception while installing 

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/Bugquery#183]
After accepting terms (While installing from the market) i am getting this exception
`An error occurred while collecting items to be installed
session context was:(profile=_home_sazulay3_eclipse_java-neon2_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.google.gson,2.7.0.v20170129-0911
No repository found containing: osgi.bundle,com.gradleware.tooling.client,0.19.0.v20170412105839
No repository found containing: osgi.bundle,com.gradleware.tooling.model,0.19.0.v20170412105839
No repository found containing: osgi.bundle,com.gradleware.tooling.utils,0.19.0.v20170412105839
No repository found containing: osgi.bundle,org.eclipse.buildship.branding,2.0.2.v20170420-0909
No repository found containing: osgi.bundle,org.eclipse.buildship.core,2.0.2.v20170420-0909
No repository found containing: osgi.bundle,org.eclipse.buildship.stsmigration,2.0.2.v20170420-0909
No repository found containing: osgi.bundle,org.eclipse.buildship.ui,2.0.2.v20170420-0909
No repository found containing: osgi.bundle,org.eclipse.mylyn.bugzilla.core,3.23.1.v20170623-0008
No repository found containing: osgi.bundle,org.eclipse.mylyn.bugzilla.ide,3.23.0.v20170411-2108
No repository found containing: osgi.bundle,org.eclipse.mylyn.bugzilla.ui,3.23.1.v20170623-0008
No repository found containing: osgi.bundle,org.eclipse.mylyn.builds.core,1.15.0.v20170411-2141
No repository found containing: osgi.bundle,org.eclipse.mylyn.builds.ui,1.15.0.v20170411-2141
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.core,3.23.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.identity.core,1.15.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.net,3.23.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.notifications.core,1.15.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.notifications.feed,1.15.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.notifications.ui,1.15.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.repositories.core,1.15.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.repositories.http.core,1.15.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.repositories.ui,1.15.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.screenshots,3.23.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.ui,3.23.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.workbench,3.23.0.v20170503-0014
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.xmlrpc,3.23.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.context.core,3.23.0.v20170411-2108
No repository found containing: osgi.bundle,org.eclipse.mylyn.context.tasks.ui,3.23.0.v20170411-2108
No repository found containing: osgi.bundle,org.eclipse.mylyn.context.ui,3.23.0.v20170414-0629
No repository found containing: osgi.bundle,org.eclipse.mylyn.debug.ui,3.23.0.v20170411-2108
No repository found containing: osgi.bundle,org.eclipse.mylyn.discovery.core,3.23.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.discovery.ui,3.23.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.git.core,1.15.0.v20170411-2003
No repository found containing: osgi.bundle,org.eclipse.mylyn.git.ui,1.15.0.v20170411-2003
No repository found containing: osgi.bundle,org.eclipse.mylyn.help.ui,3.23.1.v20170623-0008
No repository found containing: osgi.bundle,org.eclipse.mylyn.hudson.core,1.15.0.v20170411-2141
No repository found containing: osgi.bundle,org.eclipse.mylyn.hudson.ui,1.15.0.v20170411-2141
No repository found containing: osgi.bundle,org.eclipse.mylyn.ide.ant,3.23.0.v20170411-2108
No repository found containing: osgi.bundle,org.eclipse.mylyn.ide.ui,3.23.0.v20170411-2108
No repository found containing: osgi.bundle,org.eclipse.mylyn.java.tasks,3.23.0.v20170411-2108
No repository found containing: osgi.bundle,org.eclipse.mylyn.java.ui,3.23.0.v20170411-2108
No repository found containing: osgi.bundle,org.eclipse.mylyn.monitor.core,3.23.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.monitor.ui,3.23.0.v20170411-1844
No repository found containing: osgi.bundle,org.eclipse.mylyn.resources.ui,3.23.0.v20170411-2108
No repository found containing: osgi.bundle,org.eclipse.mylyn.tasks.bugs,3.23.1.v20170623-0008
No repository found containing: osgi.bundle,org.eclipse.mylyn.tasks.core,3.23.1.v20170623-0008
No repository found containing: osgi.bundle,org.eclipse.mylyn.tasks.index.core,3.23.1.v20170623-0008
No repository found containing: osgi.bundle,org.eclipse.mylyn.tasks.index.ui,3.23.1.v20170623-0008
No repository found containing: osgi.bundle,org.eclipse.mylyn.tasks.search,3.23.1.v20170623-0008
No repository found containing: osgi.bundle,org.eclipse.mylyn.tasks.ui,3.23.1.v20170623-0008
No repository found containing: osgi.bundle,org.eclipse.mylyn.team.ui,3.23.0.v20170411-2108
No repository found containing: osgi.bundle,org.eclipse.mylyn.versions.core,1.15.0.v20170411-2003
No repository found containing: osgi.bundle,org.eclipse.mylyn.versions.ui,1.15.0.v20170411-2003
No repository found containing: osgi.bundle,org.gradle.toolingapi,3.5.0.v20170412105839
No repository found containing: osgi.bundle,com.google.guava,21.0.0.v20170206-1425
No repository found containing: osgi.bundle,org.apache.commons.codec,1.9.0.v20170208-1614
No repository found containing: osgi.bundle,org.apache.httpcomponents.httpclient,4.5.2.v20170210-0925
No repository found containing: osgi.bundle,org.apache.httpcomponents.httpcore,4.4.6.v20170210-0925
No repository found containing: osgi.bundle,org.apache.lucene.analyzers-common,6.1.0.v20161115-1612
No repository found containing: osgi.bundle,org.apache.lucene.core,6.1.0.v20161115-1612
No repository found containing: osgi.bundle,org.apache.lucene.queryparser,6.1.0.v20161115-1612
No repository found containing: org.eclipse.update.feature,org.eclipse.buildship,2.0.2.v20170420-0909
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.bugzilla_feature,3.23.1.v20170623-0008
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.builds,1.15.0.v20170411-2141
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.commons,3.23.0.v20170503-0014
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.commons.identity,1.15.0.v20170411-1844
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.commons.notifications,1.15.0.v20170411-1844
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.commons.repositories,1.15.0.v20170411-1844
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.commons.repositories.http,1.15.0.v20170411-1844
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.context_feature,3.23.0.v20170414-0629
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.discovery,3.23.0.v20170411-1844
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.git,1.15.0.v20170411-2003
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.hudson,1.15.0.v20170411-2141
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.ide_feature,3.23.0.v20170411-2108
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.java_feature,3.23.0.v20170411-2108
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.monitor,3.23.0.v20170411-1844
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.tasks.ide,3.23.1.v20170623-0008
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.team_feature,3.23.0.v20170411-2108
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.versions,1.15.0.v20170411-2003
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn_feature,3.23.1.v20170623-0008`

**Comment by yosefraisman** [comment]
Please download a current version of Eclipse ([Try this one](https://www.eclipse.org/downloads/packages/eclipse-ide-java-developers/neon3)). You could use a different installation method, too. Let me know if you run into more problems.

Also, you can try [the website](http://ssdlbugquery.cs.technion.ac.il/) while the plugin installs.

**Comment by yosefraisman** [comment]
@shimonAzulay

**Comment by shimonAzulay** [comment]
@yosefraisman I will try and let u know

**Comment by zahimizrahi** [comment]
me too. I solved it by trying to install in different way (there are some ways)

**Comment by shimonAzulay** [comment]
Ok, so i tried the website option on my current eclipse version and still i am getting exception,
I tried your suggestion @yosefraisman and download eclipse neon 3 from your Link and now it works from the Market Place.

Check the exception : i used eclipse neon 2

**Comment by yosefraisman** [comment]
Things are working fine now, then?
