### ISSUE TITLE
found results on exception, but results appear with no 'Accepted Answer' 

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/Bugquery#186]
Hi BugQuery, 

I tried to search for this exception in your system and it shows result with no 'Accepted Answer': 

![image](https://user-images.githubusercontent.com/23057130/27769228-347c8cba-5f2e-11e7-886f-08695a92ec92.png)

**Comment by ZivIzhar** [comment]
That means there was no accepted answer :)
To see the other answers click on the topic name and see the original stackoverflow post.

**Comment by zahimizrahi** [comment]
so what is difference between there was no accepted answer, and something like what you did there?

![image](https://user-images.githubusercontent.com/23057130/27769396-1a540d38-5f31-11e7-9814-c0c19b19f5bd.png)


Here, too, there was no accepted answers but I still can see the 'Best Answer' tab...

**Comment by yonzarecki** [comment]
We didn't update the example pages to the current format.
Thanks for noticing.

**Comment by zahimizrahi** [comment]
was it updated?

**Comment by zahimizrahi** [comment]
sorry for reopening, but it is still not solved:
check here - http://ssdlbugquery.cs.technion.ac.il/examples/IllegalStateException

**Comment by yonzarecki** [comment]
It looks solved to me..
