### ISSUE TITLE
can't isolate console output from trace?

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/Bugquery#188]
![selection_029](https://user-images.githubusercontent.com/20992584/27769294-ac570ae8-5f2f-11e7-8d74-32b893604438.png)
<br>
but for next program:<br>
![selection_030](https://user-images.githubusercontent.com/20992584/27769298-bc8787d0-5f2f-11e7-94c6-9378783ccc4f.png)
<br>
I receive:<br>
![selection_031](https://user-images.githubusercontent.com/20992584/27769305-c773c5f0-5f2f-11e7-87ad-7415ee9fcc63.png)<br>
while "hello" is clearly a console output.<br>

**Comment by nikitadizhur** [comment]
then can you, please, make it more clear for user, whether in your user manual or in the result window?

**Comment by yossigil** [comment]
Team: close please after fixing the guide

**Comment by mdoron** [comment]
Updated

**Comment by yossigil** [comment]
:+1:
