### ISSUE TITLE
question about the user giude

### ISSUE THREAD

**Issue by assaflu** [TechnionYP5777/Bugquery#189]
in the guide it was specified to use the icon 
![image](https://user-images.githubusercontent.com/16488251/27769321-e7fd4346-5f2f-11e7-9984-86273d9437cd.png)
but the only icon that appear is 
![image](https://user-images.githubusercontent.com/16488251/27769329-ffda85be-5f2f-11e7-88f5-35e308db8723.png)

can anyone explain the difference and why i dont see the first mentioned icon?

**Comment by yosefraisman** [comment]
Hi Asaf, that icon appears in the BugQuery menu in the Eclipse menubar (it's the first command). I cleared that up in the guide, for future users. Thanks!

![Imgur](http://i.imgur.com/3JPAxq3.png)

**Comment by yossigil** [comment]
Great job @yosefraisman
