### ISSUE TITLE
lines in which the error occurred aren't marked?

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/Bugquery#192]
In user manual is written:<br>
![](https://raw.githubusercontent.com/TechnionYP5777/UpAndGo/d64b71e2ad3901601eeeeaf7a82d9490798b00b0/6.png)<br>
but they are not?<br>
![](https://raw.githubusercontent.com/TechnionYP5777/UpAndGo/d64b71e2ad3901601eeeeaf7a82d9490798b00b0/7.png)<br>
<br><br>
Are there some conditions on which markdown is shown?

**Comment by yosefraisman** [comment]
Did you choose the project from the drop-down menu as the guide requested?

**Comment by yosefraisman** [comment]
@nikitadizhur Did you choose the project from the drop-down menu as the guide requested? [link](https://github.com/TechnionYP5777/Bugquery/wiki/User-Guide#quickly-solve-bugs)

**Comment by nikitadizhur** [comment]
@yosefraisman, yes

**Comment by yosefraisman** [comment]
@nikitadizhur Could you screenshot the Markers view? got to `Window`->`Show View`->`Other...` then pick `Markers`

**Comment by nikitadizhur** [comment]
Here there are:
![selection_034](https://user-images.githubusercontent.com/20992584/27787587-edb6c618-5fed-11e7-9932-a157c411f455.png)

**Comment by yosefraisman** [comment]
Thank you, we are trying to replicate the problem in our machines!

**Comment by yosefraisman** [comment]
We couldn't replicate the problem, everything works fine in our side. Could you send an archive of your project? make sure you are using the latest version of Eclipse as well.

**Comment by yosefraisman** [comment]
Wait, did you click the BugQuery icon above the console or initiated the app in a different way (like pressing `ctrl+6`)? we can't generate markers until you run a query.

**Comment by nikitadizhur** [comment]
[BugQueryTest.zip](https://github.com/TechnionYP5777/Bugquery/files/1119141/BugQueryTest.zip)

**Comment by nikitadizhur** [comment]
@ yosefraisman it happens even after I run query by clicking the BugQuery icon above the console

**Comment by mdoron** [comment]
We downloaded your project and runned our plugin. It seems fine on our machines. Be sure you are doing the following steps (as written in our user manual):
1. Open the project.
2. Choose the project in the BugQuery -> Choose project... -> <yourproject> menu
3. Press the BugQuery button or press the combination Ctrl+6

**Comment by yosefraisman** [comment]
They still don't show it markers view too?

**Comment by nikitadizhur** [comment]
@yosefraisman, @mdoron now it shows like that:
![](https://user-images.githubusercontent.com/20992584/27788583-e5bb7aea-5ff1-11e7-8c6f-129a7d58ae32.png)

**Comment by yosefraisman** [comment]
Looks like it's working. Why do you think it didn't work initially?

**Comment by nikitadizhur** [comment]
Maybe because of multiple warnings in the line.

but anyway, it isn't showing "BugQuery has a solution for this problem..." or something like that

**Comment by yosefraisman** [comment]
Double click the marker, nothing pops up?

**Comment by nikitadizhur** [comment]
yes, my bad, I didn't know that you have to click on it.
then you can say that problem is solved, somehow

**Comment by yosefraisman** [comment]
Great, thank you.
