### ISSUE TITLE
cannot find complicated exceptions

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/Bugquery#193]
I used the exception from this issue: https://stackoverflow.com/questions/11282599/setup-oracle-11g-in-integration-of-jsf-spring-hibernate

but when i try to search for it in, i get tv error: 
![image](https://user-images.githubusercontent.com/23057130/27787497-9a7bcffc-5fed-11e7-9c56-63a2aea55fd4.png)

**Comment by rodedzats** [comment]
This exception happens when there are no matching results in our db, it says "No results" (Not - typo). We are pushing right now a new version to our server in which the output will be "Bugquery found 0 results" instead of this exception. This issue is similar to #185, #187 . Closing.

**Comment by rodedzats** [comment]
It is available now, no need to update plugin the change is in the website.
