### ISSUE TITLE
Sometimes chosen project is shown as not chosen

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/Bugquery#194]
I think there is a bug in GUI: (happens sometimes)
1. I choose project:
![](https://raw.githubusercontent.com/TechnionYP5777/UpAndGo/7688f73180b12cd779cdb5f656da70732ac179da/8.png)
2. Then I press Run As... Java Application.
3. Then I reopen BugQuery tab:
![](https://user-images.githubusercontent.com/20992584/27788234-75e2b720-5ff0-11e7-92c3-c12f1a8c7b96.png)
And the project is shown as not chosen.
4. Then I drag the mouse over the tab and it suddenly shows as chosen.

**Comment by yosefraisman** [comment]
Known issue of the Eclipse program in Linux, thanks. In windows and macOS it works fine.
