### ISSUE TITLE
Trace Marker works only once

### ISSUE THREAD

**Issue by geniashand** [TechnionYP5777/Bugquery#196]
When running the code the first time and getting an exception it is shown in the Trace Marker, however, running different code won't mark the other line.

I ran this program 
![image](https://user-images.githubusercontent.com/23057153/27788558-d08d666a-5ff1-11e7-9758-080b89ad1b41.png)

And got the following trace stack:
![image](https://user-images.githubusercontent.com/23057153/27788614-018b05a6-5ff2-11e7-8932-44160aecf1d3.png)

In the trace marker:
![image](https://user-images.githubusercontent.com/23057153/27788653-1edbd6bc-5ff2-11e7-8a7b-eeba50af0861.png)

When running the following code:
![image](https://user-images.githubusercontent.com/23057153/27788715-5e5c4ec0-5ff2-11e7-8518-f6bff5e02279.png)

And getting the following stack trace:
![image](https://user-images.githubusercontent.com/23057153/27788686-3ec939d8-5ff2-11e7-8662-7d08708c34c7.png)

However, the trace marker still shows:
![image](https://user-images.githubusercontent.com/23057153/27788752-813463e2-5ff2-11e7-93b2-992c14311360.png)

**Comment by yosefraisman** [comment]
Looking into it, thanks.

**Comment by mdoron** [comment]
@geniashand Can you be more specific? We didn't really understand what is you case

**Comment by geniashand** [comment]
It should show also the exception of ArrayIndexOutOfBound in the TraceMarker (or only it without the previous one)
However, the trace marker shows only the exception thrown in the first run (file exception), the second run throws a different exception(ArrayIndexOutOfBound) but it's not shown in the TraceMarker

**Comment by mdoron** [comment]
did you press the bugquery button once again?

**Comment by geniashand** [comment]
Seems like pressing the plugin icon solves the problem, thought it was supposed to be automatic
Thanks!
