### ISSUE TITLE
Create algorithm for getting relevant stack traces from db

### ISSUE THREAD

**Issue by rodedzats** [TechnionYP5777/Bugquery#20]
As we discussed in the last weekly meeting, we need an algorithm which will receive an input stack trace and will output the best matching stack traces which exist in our database. The output will also contain the matching stackoverflow data (the data which is saved in the db) with the relevant stack traces. 
The matching will be made using the algorithms from #8 .

**Comment by yossigil** [comment]
Much more concrete is to implement a class with stub functions and then define the issue as filling in the missing functions.

**Comment by AdiOmari** [comment]
You are definitely right, but since they are the same sub-team that use the function, they are given the freedom to define both the stub and the implementation.

**Comment by yossigil** [comment]
Good point! Sure.
