### ISSUE TITLE
markings don't disapear even when code is changed

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/Bugquery#201]
when I change the code and error marking aren't relevant they are still appear.

**Comment by mdoron** [comment]
It's known. We decided not to do it because they might be still relevant. We want only to remove t he markers between launches. Thank you

**Comment by nikitadizhur** [comment]
@mdoron I launch application (Run as... Java application) and it still remains

**Comment by nikitadizhur** [comment]
@mdoron, to clarify:
If Marking was about one exception and the I put another one instead of it on the same line, the marker still shows the previous exception

**Comment by mdoron** [comment]
And after the new launch did you press the bug query button one more time?

**Comment by mdoron** [comment]
see #196

**Comment by mdoron** [comment]
@nikitadizhur okay?

**Comment by nikitadizhur** [comment]
@mdoron, yes it seems to be the case.
but it's really annoying that i see markers about things that aren't relevant anymore.
can you, please, write about this somewhere in guide, or somewhere else, because it's not so obvious?

**Comment by mdoron** [comment]
Will do

**Comment by nikitadizhur** [comment]
thanks

**Comment by mdoron** [comment]
Updated: "After every launch you'll need to press the BugQuery button again (or to press `Ctrl`+`6`) in order to place the markers again in the right position."
