### ISSUE TITLE
Send Trace to Browser

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#21]
Decide on, and implement in `class SendTrace`, a function that open up a webpage with the trace we got as input (replacing the current stub, which prints out the trace to a `MessageDialog`).
#### Options:
- `Desktop.getDesktop().browse(new URL(url).toURI());` (leading answer in Stackoverflow, crashed in my Linux testing. Also, some eclipse alternatives are available, so they are naturally more attractive.)
- Using `org.eclipse.swt.program` (find an external Browser, and then use `Program.launch(url)`. Makes the most sense, probably easiest in implementation.)
- Use an SWT Browser, as demonstrated in [eclipse.org/swt/snippets](https://www.eclipse.org/swt/snippets/).
- `PlatformUI.getWorkbench().getBrowserSupport().getExternalBrowser().openURL(url)` (from `Interface IWorkbenchBrowserSupport`. Should work, but it's mainly used for the internal browser from what I can gather.)

Temporarily, `url` will be some version of `"https://www.google.com/#q=" + trace + " site:stackoverflow"`

**Comment by yosefraisman** [comment]
Successfully implemented. Once we have a version of BugQuery online, we'll revisit.

**Comment by yosefraisman** [comment]
We have a version running on a Tomcat server. Enhanced `class SendTrace` to support sending a GET request to the server in `localhost:8080`.

**Comment by yossigil** [comment]
:+1:
