### ISSUE TITLE
Convert project to Maven

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Bugquery#23]
Create a pom.xml etc. Change folder structure.

@AdiOmari reassign.

**Comment by AmitOhayon** [comment]
@yossigil correct me if I am wrong, but (at least for the serverside) the project is already a Maven project

**Comment by yossigil** [comment]
It is!!! Better if you create a parent Maven and two daughters. Feel free to adjust labels and/or delay a bit.

**Comment by AmitOhayon** [comment]
@yossigil excuse my for my lack of knowledge about Maven, are you referring to a Maven project with multiple modules?

**Comment by yossigil** [comment]
Yes.

**Comment by yossigil** [comment]
:+1:
