### ISSUE TITLE
Initial Design of the Website

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#24]
Design and implement in HTML and CSS the basic layout of bugquery.com, creating templates for a homepage, search pages (a form and a page for search results), and a user guide (with content).

**Comment by yosefraisman** [comment]
Attached are screenshots of the static pages I made for the website.
### Homepage
![screenshot from 2016-12-12 13-07-40](https://cloud.githubusercontent.com/assets/16455692/21097279/7cde60de-c06c-11e6-9e84-4d0068538cd3.png)
### User Guide
![screenshot from 2016-12-12 13-07-45](https://cloud.githubusercontent.com/assets/16455692/21097280/7d0c382e-c06c-11e6-943d-f99cb000b596.png)

### Search Results
![screenshot from 2016-12-12 13-07-50](https://cloud.githubusercontent.com/assets/16455692/21097283/7dab3866-c06c-11e6-9c64-b9d1fa63845c.png)
### Search Form
![screenshot from 2016-12-12 13-07-54](https://cloud.githubusercontent.com/assets/16455692/21097282/7dab0c74-c06c-11e6-8ae5-5e9c2e9fc86d.png)

**Comment by AmitOhayon** [comment]
Merged into #17

**Comment by yossigil** [comment]
Excellent work @yosefraisman #4 @AdiOmari

**Comment by AdiOmari** [comment]
Looks nice! @AmitOhayon and @yosefraisman
