### ISSUE TITLE
Setting up environment in the server

### ISSUE THREAD

**Issue by ZivIzhar** [TechnionYP5777/Bugquery#25]
- [x] Setting up the git

- [ ] Setting up the mysql server

- [x] Installing Eclipse.

- [x] Installing tomcat

- [x] Configuring tomcat server

- [x] Download StackOverflow posts to the server - download in progress

Will probably add more while working in the server

**Comment by ZivIzhar** [comment]
After agonizing time with eclipse and tomcat, I managed to run the website as a local server on the csl server. ( @AmitOhayon I know your pain now. )

I will update the wiki guide for installing the environment to be a little more clear and dummy proof.

Note (Also will be added in the wiki): The tomcat server configurations are saved in the local eclipse's workspace.

**Comment by ZivIzhar** [comment]
Another **important** note:
In order to keep the **csl server** as organized as possible, all our files are under "**D:\BugQuery Project\**"

**Comment by ZivIzhar** [comment]
Regarding the MySQL server on the csl server, In order to not affect adi's databases, we can use another instance as shown in here: http://dev.mysql.com/doc/refman/5.7/en/multiple-windows-command-line-servers.html

**Comment by tonylekhtman** [comment]
Succefully installed new mysql server on the server.
Ran a sample program on the server and it worked. #9

**Comment by yossigil** [comment]
:+1:

**Comment by tonylekhtman** [comment]
Finished downloading the posts.xml and extracting it. The work on the db continues in #9.
Closed.
