### ISSUE TITLE
Represeting stack-traces better

### ISSUE THREAD

**Issue by rodedzats** [TechnionYP5777/Bugquery#26]
Now we represent stack trace as a simple string. We need to create a stack-trace object which will contain more informative details about the stack trace, such as the type of the exception and a list of all the error sentences. 
After that we need to change the already implemented algorithms to use this entity.

To summarize we need to:
- [x]  Create a stack trace object which will contain more info.
- [ ] Change existing algorithms to use this entity

**Comment by yonzarecki** [comment]
Looking for places where Strings are used instead of the "StackTrace" entity
