### ISSUE TITLE
Add tests to com.bugquery.serverside.stacktrace

### ISSUE THREAD

**Issue by ZivIzhar** [TechnionYP5777/Bugquery#27]
Add tests and increase the test coverage rate.

**Comment by ZivIzhar** [comment]
com.bugquery.serverside.stacktrace test coverage is not 97.6% (the uncoveraged lines are static classes default constructures).

**Comment by AdiOmari** [comment]
@ZivIzhar  So the algorithm misses some stack trace lines? that is what you mean. Please discuss it with @yonilx, if they are not important (at the end of the trace) and hard to include (affect precision) then leave it as is.

**Comment by ZivIzhar** [comment]
What I meant is that because these classes only have static methods, there are no objects of this class, therefore the coverage drops. It's basicly means 100% coverage.

**Comment by AdiOmari** [comment]
👍
