### ISSUE TITLE
Access to MySQL on csl server

### ISSUE THREAD

**Issue by ZivIzhar** [TechnionYP5777/Bugquery#29]
We are unable to use the mysql in the csl server since there is already a mysql server installed and we dont have the password for it.

username root & password root doesn't work.

**Comment by AdiOmari** [comment]
@ZivIzhar You can unistall/reinstall mysql, I've checked and found that the current site hosted does not use a database (If you wonder what it is, it is a classifier, check it if you like at: [largestack.org](url)).

**Comment by tonylekhtman** [comment]
Done.
Uninstalled and installed new one.
