### ISSUE TITLE
Add Missing Team Members

### ISSUE THREAD

**Issue by AmitOhayon** [TechnionYP5777/Bugquery#3]
@zvili Please add the rest of the team:
[rodedzats](https://github.com/rodedzats)
[ZivIzhar](https://github.com/ZivIzhar)
[yosefraisman](https://github.com/yosefraisman)
And Adi, our project leader (I don't have his profile)

**Comment by zvili** [comment]
@AmitOhayon 
rodedzats has not yet subscribed to GitHub :-1: 
Zivlzhar has not yet subscribed to GitHub :-1: 
Which Adi are you refering to ? :-1:

**Comment by yosefraisman** [comment]
Here's Adi's profile: @AdiOmari. What do you mean by "not subscribed to GitHub"? Thank you!

**Comment by yonzarecki** [comment]
Can you add @rodedzats 's and @ZivIzhar 's Karma pages ? They joined the Bugquery project

**Comment by zvili** [comment]
added - @rodedzats's and @ZivIzhar's Karma pages.

**Comment by yossigil** [comment]
@AmitOhayon : how come this issue 
1. has no labels
2. has no milestone
3. has no assignee
4. is still open

@zvili @idabran @yh-github @AdiOmari @orimarco

**Comment by yonzarecki** [comment]
All missing team members are in this project.
