### ISSUE TITLE
Use HTTP POST for Stack Trace Submission

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#30]
Replace our simple HTTP GET request interface with more complex HTTP POST requests. A POST request isn't (theoretically) limited in size, and thus is more suitable for submitting long-form stack traces which could potentially exceed some size limits of the HTTP GET request.

### Current Idea for Implementation
1. Log every POST request (using hashing) in a list of current submissions.
2. Reply to each POST request with that hash (index).
3. Create a matching page in our site with the results.

### Progress (this is a big one)
- [x] Implement a web application on our Eclipse server, that handles trace submission using HTTP POST
- [x] Change plug-in behavior accordingly
- [x] Change the website's submit form page accordingly

**Comment by yossigil** [comment]
:+1:

**Comment by AmitOhayon** [comment]
reading about [jersey and MVC](https://jersey.java.net/documentation/latest/mvc.html) to make the website's design (code-wise) more elegant and robust before continuing

**Comment by yossigil** [comment]
Talk to @leyaniv. He was leading a major effort towards MVC in his group.

**Comment by AmitOhayon** [comment]
@yossigil I am familiar with the concept of MVC (thanks to 236700), I just never done it on a web application, certainly not a Java web application, and from what I can tell they do not deal with this problem.

Maybe you or @AdiOmari could help me with a related question I have - the reason I chose jersey is because I saw it earlier this semester on another course, but not in this context. Maybe I should go with another framework, like Spring? Or stick with plain JSP? I would appreciate your opinion

**Comment by AdiOmari** [comment]
@AmitOhayon  I think jersey seems to be good for our needs. I didn't use it before (I use angularjs and -yossi ignore this- asp.net), but from reading it seems like a good fit.

**Comment by AmitOhayon** [comment]
having trouble with jersey, trying to study it on a simpler example before messing with our existing code

**Comment by yossigil** [comment]
:+1:  @AmitOhayon

**Comment by AmitOhayon** [comment]
Having some progress but learning by trial and error is very difficult and time consuming.
Maybe we should open a new issue for MVC and progress in these two areas separately, because right now it is blocking the POST method progression.
What do you think @yosefraisman @AdiOmari ?

**Comment by yosefraisman** [comment]
This issue will be fixed by the re-implementation of the website. Closing.

**Comment by AmitOhayon** [comment]
Apparently writing "closes" in the same commit with issue number closes it, even if they are not next to each other...

**Comment by AmitOhayon** [comment]
Website is ready, need to link the Plugin
@yosefraisman I used Id for searches instead of hashes, and you get the link to the search in the response to the POST method - this is the link you should use.

**Comment by yosefraisman** [comment]
Successfully implemented the POST request interface in the plugin, disregarding my previous implementation with `Apache HttpComponents` because of Maven issues. Now on to figure out why "=" gets printed at the end of every trace (and how to get rid of it).

**Comment by AmitOhayon** [comment]
Adjusted the website's submit form and now everything works, though because HTML form has to send a key-value formatted POST, there is a slightly different handling for traces sent from plugin and traces sent from website. @yosefraisman and I will decide on a uniform implementation to prevent this.

**Comment by yossigil** [comment]
:+1:
