### ISSUE TITLE
Can't do anything with git on server

### ISSUE THREAD

**Issue by tonylekhtman** [TechnionYP5777/Bugquery#31]
I tried to make a minor commit on the server and got the following error:
![image](https://cloud.githubusercontent.com/assets/7457420/21174106/e23c8dac-c1e3-11e6-9faa-ea789a8b9ad1.png)

Has someone got anything simillar?
It doesn't let me stage...

**Comment by AmitOhayon** [comment]
Yesterday something similar happened to me on another project. The problem was having this file open in another program. 
BTW, Did you change anything in the Git directory?  This seems like an odd rename, have you tried re-cloning?

**Comment by tonylekhtman** [comment]
I haven't tried re-cloning

**Comment by yossigil** [comment]
I would have rephrased it as:

- will try recloning and report
- cannot check now, will try to on Sun.

or something similar

**Comment by tonylekhtman** [comment]
I misunderstood it was a suggestion. I thought he asked me if this is the action I was trying to do when I got the error. My bad. I'll try recloning later and report.

**Comment by tonylekhtman** [comment]
recloning solved it. Thank you.
Closed.

**Comment by yossigil** [comment]
:+1: @tonylekhtman
