### ISSUE TITLE
User Input Bugs in Plug-in

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#34]
## To Fix:
- [x] Clipboard implementation doesn't work for Eclipse content in Linux: When copying content that originates in Eclipse (specifically console output) using "Trace from Clipboard", clipboard access fails (`!content.isDataFlavorSupported(DataFlavor.stringFlavor)`). Find a different way to access the clipboard in Eclipse, or remove the feature completely.
- [x] The BugQuery drop-down menu get redrawn after selecting a command in our input dialog, see demonstration below. Either implement a different method of drop-down menu generation, or find a way to override this behavior from the Dialog class we created (`ExtendedDialog`).

![Redrawing Bug](https://cloud.githubusercontent.com/assets/16455692/21203751/a6464c42-c25c-11e6-9def-d8234d8a709f.gif)
Originally reported in issue #13.

**Comment by yosefraisman** [comment]
After a few hours of debugging, the reason for the redrawing is still unclear. If you close the dialog using the x button on the top, no drop down menu appears (it does if you close using Cancel button, though). Maybe the solution is to trick the workspace and execute outside the handler somehow, or open a dummy window and close it to clear whatever's making this bug happen. Tried using several Display and Shell commands to no avail. Updates to follow.

**Comment by yossigil** [comment]
Keep up the study Yosef!

**Comment by yosefraisman** [comment]
### Update
- Changed the menu location of the user dialog command, which solves redrawing.
- Created a different method for clipboard extraction, called `fromClipboard2()`, that opens a new dialog and automatically tries to `ctrl+v` in it. Uses the brand new `class ClipboardDialog`.
- Also new icons for all the commands
