### ISSUE TITLE
Deciding on framework for the website

### ISSUE THREAD

**Issue by AmitOhayon** [TechnionYP5777/Bugquery#38]
Following great difficulties during #30 when working on serverside, and due to the will to move to MVC approach which would enable testing for the website, we decided to pause website development and research available frameworks which could make our work more productive.
There are several possible frameworks to work with:

- Jersey (Currently in use, causes great trouble)
- Spring
- Spark
- Play

and the list goes on.
Play seems promising, so right now it is our priority choice. Will update this issue with further advancements.

**Comment by AmitOhayon** [comment]
Update - Play appears to be a wrong choice for a couple of reasons:

- Overkill for our needs
- Incorporates Scala inside, which might be unacceptable by course staff, and Eclipse support is not trivial
- Difficult to include in a Maven project (uses sbt instead, as part of the Scala incorporation)

However, I have looked into Spring Boot which seems to be just what I was looking for - It is uses a close API to the one I know from Jersey, it has large community and resources online, and most importantly it is built to easily create standalone web applications without having to configure stuff (convention over configuration).
I have started conversion of our site and I think it's heading in a good direction.

**Comment by yossigil** [comment]
Final decision is: **Spring Boot**
