### ISSUE TITLE
Reordering website related files in packages

### ISSUE THREAD

**Issue by AmitOhayon** [TechnionYP5777/Bugquery#40]
_No milestone is set as it is not required for the prototype, so deadline is not yet decided_
In order to implement the website faster (to reach prototype on time), some design flaws were introduced:

- StackSearch should be in entities
- StackSearchRepository should be in repositories
- SearchController should be in controllers

Because of Spring Boot convention-over-configuration, this would require some changes to the code and is not as trivial as it may sound.

**Comment by yossigil** [comment]
Think of policy for managing the backlog
