### ISSUE TITLE
Fix branch "WIP"

### ISSUE THREAD

**Issue by AmitOhayon** [TechnionYP5777/Bugquery#43]
Due to mis-configuration of the eclipse project, problems were not displayed in eclipse and some commits introduced errors to the code. 
All work since last known working commit were moved to branch "WIP", and master branch was reverted.

**Comment by ZivIzhar** [comment]
No more errors.
Still 68 ***warnings*** to take care of, will do that tomorrow :>

**Comment by ZivIzhar** [comment]
# important note
This issue is dealt with in branch "WIP"

**Comment by AdiOmari** [comment]
@ZivIzhar why not to merge the fix with the master branch?

**Comment by ZivIzhar** [comment]
@AdiOmari Didn't have the time to do so, doing it now

**Comment by ZivIzhar** [comment]
No more errors, warnings.
We need to deal better with DBGetter and DBInitializer (remove the supress and use a more robust way to handle the relevant objects)
I will open an issue about that.
