### ISSUE TITLE
Quality work

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Bugquery#44]
1. Select and implement a java package structure, following the conventions of Java.
2. Use lower case names for package names
3. Install Continous Integration
4. Spartanize the code
5. Sort these items
6. Open issues as necessary.
7. Label this issue.
8. Make this issue high priority.

This issue was assigned at random to the team member with least number of commits. @ZivIzhar 
if this team member wants to pass it on, fine.

**Comment by ZivIzhar** [comment]
@yossigil 
Can you clarify some of the bullets?:
1. What java package? regarding what?
2. All the packages in the project already has lower case names
3. Will do
4. All the code is already spartanized
5. Sort what items?
6. What issues?
7. Done
8. Done?

**Comment by yossigil** [comment]
1: are you 'java.com'????
2: You do not have to oepn an issue for something that is done.
5: Current items...
6: Issues you need to open to resolve the missing things
8:?

**Comment by ZivIzhar** [comment]
@yossigil 
1.I think @AdiOmari bought this domain.

To make sure I understand your request:
You want me to open an issue about installing CI (since all the other things you wrote are already done)?

**Comment by yossigil** [comment]
Yes.

I thought I was pretty clear.

**Comment by AmitOhayon** [comment]
@yossigil 

from domain lookup:

> Domain Name: BUGQUERY.COM 
> Registrar URL: http://www.godaddy.com 
> Registrant Name: Adi Omari 
> Registrant Organization: AdiSoft 
> Name Server: NS73.DOMAINCONTROL.COM 
> Name Server: NS74.DOMAINCONTROL.COM 
> DNSSEC: unsigned 
>

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
One more little thing, I think you need a `.gitignore` file. Feel free to copy it from some other project

**Comment by yossigil** [comment]
👍 @ZivIzhar
