### ISSUE TITLE
Continuous Integration support 

### ISSUE THREAD

**Issue by ZivIzhar** [TechnionYP5777/Bugquery#47]
Add CI to our repository.

@yossigil , Apparently, in order to add CI, I need admin permissions.
Who can grant me these permissions?

**Comment by ZivIzhar** [comment]
@zvili ?

**Comment by ZivIzhar** [comment]
@yossigil @zvili @AdiOmari 
?

**Comment by yossigil** [comment]
@AdiOmari / @idabran : please take care of this.

**Comment by AdiOmari** [comment]
![image](https://cloud.githubusercontent.com/assets/5457431/21639921/6b3f228e-d27b-11e6-86be-2e7b3071b37d.png)

Done, @ZivIzhar please proceed with the configuration.

**Comment by ZivIzhar** [comment]
Done.
Since there are no tests for the plugin, I configured travis to only run serverside's junit tests.
