### ISSUE TITLE
Error Controller for the Website

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#50]
Replace the default Whitelabel Error Page ("This application has no explicit mapping for /error, so you are seeing this as a fallback.") with custom error pages (e.g., a page for the ResourceNotFoundException thrown by the SearchController when it gets an invalid id). See [Exception Handling in Spring MVC](https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc). ~No milestone yet (we'll discuss it in our meeting).~

**Comment by yossigil** [comment]
Milestone?

**Comment by yosefraisman** [comment]
Added a milestone, in accordance with today's meeting.

**Comment by yosefraisman** [comment]
![localhost-8080-stacks-14](https://cloud.githubusercontent.com/assets/16455692/21892587/356d332e-d8e0-11e6-9fd0-62a3593e4944.png)

Implemented successfully. The error page displays the Exception, and has a javascript "Show Trace" button, which loads the stack (if it's available). It looks like this:

![localhost-8080-stacks-16](https://cloud.githubusercontent.com/assets/16455692/21892730/d874607e-d8e0-11e6-9668-15e85cfefb57.png)
---
Errors with user-friendly messages (like the missing search ID exception, `throw new ResourceNotFoundException("Search id \"" + id + "\" could not be found.");`, thrown in the search controller), will render like this:
![localhost-8080-stacks-42](https://cloud.githubusercontent.com/assets/16455692/21892666/8afedc7a-d8e0-11e6-8aad-4474440e8eb0.png)

**Comment by AdiOmari** [comment]
Nice @yosefraisman, really nice!
