### ISSUE TITLE
Update DBGetter code

### ISSUE THREAD

**Issue by tonylekhtman** [TechnionYP5777/Bugquery#52]
Get all the relevant columns to our db.

**Comment by yonzarecki** [comment]
@tonylekhtman is this issue finished ?

**Comment by tonylekhtman** [comment]
No

**Comment by tonylekhtman** [comment]
Unfortunately due to personal reasons I'll be able to finish it only on Sunday.

**Comment by tonylekhtman** [comment]
Closed because irrelevant
