### ISSUE TITLE
Launch Configurations

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#54]
Use Eclipse's support of adding launch configuration types, to run the program independently through BugQuery. This will allow easier access to the threads' information, as there will be no need to sweep the terminated output consoles, just access some run-time databases. Specifically, using methods like `StackTraceElement[] getStackTrace()` from `Thread` and `Throwable`.

### Progress
- [x] Research
- [ ] Implementation

**Comment by yosefraisman** [comment]
Finished most research, but probably won't manage to close this issue before the end of the semester. Will add a new milestone after we meet.

**Comment by yossigil** [comment]
Too much work. Won't do.
