### ISSUE TITLE
Refactor serverside.stacktrace and serverside.dbparsing classes

### ISSUE THREAD

**Issue by rodedzats** [TechnionYP5777/Bugquery#55]
Clean the code and change the design to use interfaces so it'll be more generic

**Comment by yonzarecki** [comment]
We're leaving StackTraceExtractor as a static class, it's implementation should hold for all scenarios and it doesn't save any information (only utility functions).

**Comment by yonzarecki** [comment]
After reviewing the code, we decided to finish refactoring for now. 
The main result of the changes is that the code is more generic and much more testable.

Changes:
1. Created a general DB connector, abstracts the access to different types of DBs and different DB tables.

2. Created general stack-trace retrieved, this previously static object was used by the website to retrieve stack-traces, refactoring it to an interface will help create test for the website, a point for improvement we made in the past.

3. Updated test to facilitate new changes.
