### ISSUE TITLE
Update your spartanizer & handle the spartanizer tips

### ISSUE THREAD

**Issue by ZivIzhar** [TechnionYP5777/Bugquery#57]
Please update your spartanizer to the newest version and change your code to match the new changes in the spartanizer.
Right now I'm seeing 25 tips from the spartanizer.
Progress:

- [x] Ziv Izhar

- [x] Yonatan Zarecki

- [x] Roded Zats

- [x] Tony Lehktman

- [x] Amit ohayon

- [x] Yosef Raisman

**Comment by AmitOhayon** [comment]
Done for my files.
I must say, I think if one of us see this kind of mistakes he could just change it, it's only refactoring and it's not going to break anything...

**Comment by yonzarecki** [comment]
It is going to break someone's code if they're currently working on it. 
If Ziv would push an updated version of your code it would just cause a merge conflict later, this way is cleaner.

**Comment by AmitOhayon** [comment]
You've got a point. In my opinion we shouldn't be so afraid of merges but past experience says otherwise 😄

**Comment by ZivIzhar** [comment]
Since it's a broad range issue - a change of our environment, I think the best way to do so without interrupting the continuous work of others is "everyone fix their own code", instead of making everyone solve conflict issues.

**Comment by yonzarecki** [comment]
@tonylekhtman, @yosefraisman, did you finish spartanizing ?

**Comment by yosefraisman** [comment]
:+1:

**Comment by ZivIzhar** [comment]
Please pull before making any further changes, I spartanized few files
