### ISSUE TITLE
Creation of stack search page upon POST

### ISSUE THREAD

**Issue by AmitOhayon** [TechnionYP5777/Bugquery#58]
Instead of searching for results every time a user browse to a search address, we should create the results page when getting the trace from the user and save it to a database. This will save loading times for pages that already been visited at least once.

**Comment by yonzarecki** [comment]
Changing the milestone to Sprint 1, as @AmitOhayon stated he's close to finishing.
Feel free to change the milestone to a closer date.
#93

**Comment by AmitOhayon** [comment]
Currently debugging - no results found after change

**Comment by AmitOhayon** [comment]
@tonylekhtman getAllQuestionsWithTheException on com.bugquery.serverside.dbparsing.dbretriever.SQLDBConnector does not extract post id, which i later use to recover queries. Can you set the ids for retrieved MinSOPosts?

**Comment by yonzarecki** [comment]
Can I get an update on this issue ? I think it may be relevant for Google's crawling in #113

**Comment by AmitOhayon** [comment]
There is a working implementation in branch iss58, but since it is an old branch much have changed and there is also the db redesign we are doing atm so I intend to use this branch as reference only and implement again when we're done with #102

**Comment by AmitOhayon** [comment]
We ended up creating the stack search page upon first get - provides almost same functionality and needed for #70 .
