### ISSUE TITLE
Close Old Branches

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#60]
I saw there are 4 branches in the Bugquery project.
@ZivIzhar and @yosefraisman, can I close your old branches "WIP" and "post_experiment" ?
It looks like you're done working on them.

Closed :
- [x] post_experiment
- [x] WIP

**Comment by yosefraisman** [comment]
![](https://i.imgflip.com/1hjl0e.jpg)
@yonzarecki, An alternative implementation for `post_experiment` was pushed a while ago (see #30)

**Comment by yonzarecki** [comment]
Delete all old branches
