### ISSUE TITLE
Migrate to the remote MySQL server

### ISSUE THREAD

**Issue by AmitOhayon** [TechnionYP5777/Bugquery#66]
Now that we have a remote MySQL server on a VPS, we need to migrate the dbs and change the code to use it. Then we can continue working on the scheme and further enhancements.
No milestone is set because milestones haven't been discussed yet.

**Comment by tonylekhtman** [comment]
@AmitOhayon and me  Moved the old bugquery_index from the old server to the new reliable server.
Our current method for creating the index is filtering on the CSL server(it happens rarely) and exporting it to the VPS.
