### ISSUE TITLE
Plug-in Development Research, "Hello-World", Wiki Page

### ISSUE THREAD

**Issue by AmitOhayon** [TechnionYP5777/Bugquery#7]
as part of our research to understand Eclipse plugins, we will implement a simple plugin for learning purpose.

**Comment by AmitOhayon** [comment]
link to tutorial - http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Ffirstplugin.htm&cp=2_0_2

**Comment by yossigil** [comment]
Take note that we gained lots of expertise in this in the spartanizer project

**Comment by yossigil** [comment]
???????????
What's going on?

#3 : bad karma
@zvili @idabran @yh-github @orimarco @AdiOmari

**Comment by yosefraisman** [comment]
@yossigil thank you for drawing attention, this was completed and should have been closed. We experimented with several plugins and considered the options we have (some of our conclusions are available in [BugQuery: Plugin Options](https://docs.google.com/document/d/1OnSYtgwyNzTfl07NiVAXQkN-X4d347812Tt_pJF8zu0/edit?usp=sharing), and were presented in last week's meeting).

**Comment by yossigil** [comment]
Make this into a wiki page.

**Comment by yossigil** [comment]
no milestone no labels = BAD ISSUE @zvili @idabran

**Comment by yosefraisman** [comment]
Initial research's available now [as a Wiki page](../wiki/Plug-in-Development,-Initial-Research). Also, we completed our preliminary research in time for our second meeting (29.11). Should we set that as the milestone for this issue? @yossigil

**Comment by yossigil** [comment]
You were supposed to finish sprint 1, not sure what happened though...

**Comment by yosefraisman** [comment]
Added the issue to last week's milestone, closing. Thanks again!
