### ISSUE TITLE
Querying db asynchronously and refreshing when done

### ISSUE THREAD

**Issue by AmitOhayon** [TechnionYP5777/Bugquery#70]
I've been looking for a way to prevent the blank page while we wait for the queries to return. Spring support async methods as explained [here](https://spring.io/guides/gs/async-method/), but I haven't find a way to reload the page when done (or even better, replace only the relevant section in the page.
Maybe I'm missing something obvious because it has been a while since we worked with spring, let me know if you can think of something.

**Comment by AmitOhayon** [comment]
We can do this using javascript - wait for page to load ([like this](http://stackoverflow.com/questions/1033398/execute-javascript-when-page-has-fully-loaded)) and then redirect ([like this](http://stackoverflow.com/questions/4744751/how-do-i-redirect-with-javascript))

Interesting question - how will this method affect other users who are trying to use the website while someone is querying and the server is busy waiting for the mysql call. Maybe we will have to use threads?

**Comment by AmitOhayon** [comment]
I tried to use [this](http://bradsknutson.com/blog/display-loading-image-while-page-loads/) simple solution, didn't work because the page itself isn't being created until the query is done. I think there is no way around using asynchronous method for the query and somehow invoking an event to signal the page to redirect to the result. I don't have much experience with JS so I'm still researching.

**Comment by AdiOmari** [comment]
This is true. You have to use a service that checks if the page is ready
and only then redirect to the result page.

Please look in this issue here from the accessibility project for an
accelerated start with java web services (on spring):
https://github.com/TechnionYP5777/SmartCity-Accessibility/issues/238

**Comment by AmitOhayon** [comment]
I finally managed to create a page which redirects when the stacksearch is ready.
@yosefraisman agreed to try to design an animation for the loading page.
One problem with my current implementation is that it polls the page which makes an extra query to the db, so every time we send a new stacktrace we have two SELECT queries although one is only for checking the liveness of the address.
For now I'm uploading the html page without a logo and without giving an address to it, in order to show progress.

**Comment by yonzarecki** [comment]
@AmitOhayon You can work on this issue, its pretty high on our website wishlist.

**Comment by AmitOhayon** [comment]
I did, currently I am blocked until @tonylekhtman changes the SQL query for me (b1092a4)

**Comment by yonzarecki** [comment]
OK, I'll re-schedule this issue to a later date.

**Comment by tonylekhtman** [comment]
The reason this issue is needed is because we want to display a loading screen to the user while he waits for the results. We think we can do this without querying async.
Researching.
