### ISSUE TITLE
Explore how to open the bug guide in a small window

### ISSUE THREAD

**Issue by mdoron** [TechnionYP5777/Bugquery#72]
Introduction task which both me and @yosefraisman think is a good idea.
The idea is just like the help in MATLAB open a small window, I want our site would open this way in the plugin.

**Comment by mdoron** [comment]
I've managed to do so, but I think it doesn't look good. I'm trying to do it with quick fix-like interface (similar to the Tippers in Spartan project).

**Comment by mdoron** [comment]
We can now suggests fixes with the proper GUI (I left an example within SendTrace.java). Next step is actually allowing fixes in code.

**Comment by mdoron** [comment]
In second thought, I want to see if I can improve this a little bit. I will keep this open for now.

**Comment by yonzarecki** [comment]
@mdoron are you still working on this issue ? 
#93

**Comment by mdoron** [comment]
@yonzarecki Yes but now this goes under research again, correspondingly to what was discussed with Yosi.

**Comment by yonzarecki** [comment]
👍

**Comment by mdoron** [comment]
So, short summary + update:
At the beginning I thought we should add a small window to the eclipse plugin which will hold  a simple explanation from the server about the cause for the bug we have. I wanted it to be over the lines which caused the exception. So the first lead was to implement something like we have in the Spartanizer project, using IMarkers etc. I implemented something simple to check if it's working and it was nice, but not enough. Then, @yossigil offered we won't use the markers, but something else, since this is not the right way to do such explanations. I searched a little bit and realized we should implement a _Hover Help_.
So this is what I'm working on now - trying to understand how to do it the right way and add it to the project.

**Comment by mdoron** [comment]
# סיכום מחקר
## מטרת הרעיון
לקבל stack-trace, ובקבצים המתאימים בשורות המתאימות להניח הודעת המלצה מהשרת לגבי השגיאה. המחקר בוצע כדי לקבל הערכה כיצד לממש בצד הפלאגין.
## תיאור המחקר
בתחילה חקרתי את נושא ה markerים והצלחתי לקבל מספר שורה (אפילו בהתאם לשגיאה שקיבלנו למרות שהנושא הזה לא פותח במלואו בעקבות דברים אחרים) ולהציג עליה הודעת שגיאה. לאחר מכן בעקבות השיחה עם המנחה הגענו למסקנה שה markerים במקורם מיועדים למנגנון של quickfix והוא לא המנגנון המדויק שאנחנו רוצים, כי הוא מיועד יותר לממש תיקון בקוד, דבר שאנחנו לא עושים. בעקבות כך פניתי למחקר של hover text לעומק כ lead מרכזי, וגיליתי שבמנגנון שם מה שקורה זה שאם מציבים את הסמן על איזשהו region אנחנו יכולים לקבל אותו ואז לבצע משהו. שמתי לב שאנחנו מצד אחד רוצים לקבל את ההתנהגות של marker שאפשר לסמן מקומות מסויימים ועליהם לקבל איזשהו מטה-דטה, ומצד שני לא לאפשר באמת מצב של quick fix. לא מצאתי מנגנון אחר שמשלב בין השניים.
# תוצאות ביניים ומסקנות
* הצלחתי לגרום לשני החלקים לעבוד בנפרד כאבי-טיפוס.
*  אחרי מחקר מעמיק יחסית הגעתי למסקנה שלא קיים באקליפס מנגנון שמתאים לנו באופן ישיר. חקרתי את הנושא והגעתי למסקנה שצריך לחשוב על דרך שלא נמצאת בצורה ישירה באקליפס לחבר בין שני המנגנונים הללו (quickfix+hover text), כלומר ליצור איזשהו מנגנון עוטף.
* לחלופין, אפשר לממש הכל דרך מנגנון ה quickfix, מה שיהיה קל יותר, ולהתפשר על כך שזה לא היעוד המקורי שלו.
הצעות וצעדים להמשך
* יש להתייעץ עם המנחה @yossigil לגבי המנגנון הנכון לביצוע המטלה.
* יש להתייעץ עם הלקוח @AdiOmari, להציג לו את המחקר, ולבדוק האם הדבר מספיק חשוב לו כדי שנשקיע זמן על פיתוח מנגנון עוטף או שהוא היה רוצה לראות דברים נוספים בפלאגין, ואפשר להתפשר על הפתרון השני.

**Comment by yonzarecki** [comment]
I'd say this issue is finished, isn't it ? @mdoron

**Comment by mdoron** [comment]
Definitely.
