### ISSUE TITLE
Plug-in Wishlist

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#74]
As the main goal set for this week in our meeting, @mdoron suggested we open an issue for suggestions regarding the future development of the plug-in this semester. We will be happy to receive suggestions from everyone in the comments.

**Comment by yosefraisman** [comment]
### My Wishlist
- Implementation of #54 launch configuration, which I think will be my main mission this semester.
- Restructure, remove old unused code.
I'll edit this comment if I come up with more ideas.

**Comment by mdoron** [comment]
* Tracking changes in code for stack trace examples of fixes

**Comment by mdoron** [comment]
@yosefraisman I added this to the [project](https://github.com/TechnionYP5777/Bugquery/projects/1). Change as you wish.
