### ISSUE TITLE
Tomcat maven dependency

### ISSUE THREAD

**Issue by ZivIzhar** [TechnionYP5777/Bugquery#75]
- [ ] Add Tomcat as a maven dependency

As much as I can see, there is an option to add tomcat as a maven dependency.
Which means - there will be no need to download tomcat separately (one less pain to deal with).
Furthermore, the tomcat files will be with all the other project's files.

**Comment by AmitOhayon** [comment]
You don't need tomcat separately anymore, it is embedded in the application (thanks to spring). 
Closing
