### ISSUE TITLE
Change the database access to use the spring framework

### ISSUE THREAD

**Issue by tonylekhtman** [TechnionYP5777/Bugquery#76]
Change the data access from using strings(jdbc) to using objects(ORM), creating a virtual object database. Making the access more object oriented.

**Comment by tonylekhtman** [comment]
Making a sample using this guide:
https://spring.io/guides/gs/accessing-data-mysql/#scratch

**Comment by AmitOhayon** [comment]
After a research, @tonylekhtman and myself have figured out how to store entities with embedded classes, and we made a simple demo project which seems to work. So research phase seems to be over, now we need to implement on our project

**Comment by AdiOmari** [comment]
Nice work guys!

**Comment by tonylekhtman** [comment]
Encountered a bug.
The StackOverflowRepository is null after I start the application but it should be autowired via the spring boot. Currently debugging this issue.

**Comment by AmitOhayon** [comment]
helped @tonylekhtman with debugging and the problem was solved

**Comment by yonzarecki** [comment]
Hey guys, is this issue finished ?

**Comment by AmitOhayon** [comment]
In progress, @tonylekhtman is on it

**Comment by tonylekhtman** [comment]
As stated in #102 @AmitOhayon and I have come to conclusion ORM is not the right way for us. Further discussion regarding db design will continue on #102 .
closing.Won't do.

**Comment by yonzarecki** [comment]
@tonylekhtman Is this branch still needed ?

![selection_008](https://cloud.githubusercontent.com/assets/23148393/26275430/abb47fdc-3d68-11e7-86de-5ed9a25d3b55.png)

**Comment by tonylekhtman** [comment]
No
