### ISSUE TITLE
Add functionality to StackTrace.java parser to fit new plugin feature

### ISSUE THREAD

**Issue by mdoron** [TechnionYP5777/Bugquery#78]
From stack trace extract lines, files, exception, etc. We need this specifically in order to mark the right position (the line(s)) which yields the exception, but I'm sure we'll find what to do with entire class of parsing.

If the guys who worked on the similarity function did something like this, please inform @rodedzats @yonzarecki.

FYI: @yosefraisman 

Clarification: We need a way to get the line numbers of the stack trace.

**Comment by yonzarecki** [comment]
I think we did something similar, we'll look into that later today.

**Comment by rodedzats** [comment]
@mdoron check the StackTrace class, it has this functionality

**Comment by mdoron** [comment]
@rodedzats I only say it extract stack trace if it exists, but not specific details within it - I'm talking about ExtractTrace.java.

**Comment by rodedzats** [comment]
@mdoron check this class: https://github.com/TechnionYP5777/Bugquery/blob/master/BugQueryServerSide/src/main/java/com/bugquery/serverside/entities/StackTrace.java
It extracts the stack trace and saves the exception type and the stack of calls

**Comment by mdoron** [comment]
Tremendous! I will add some functionality right ahead. Is this code going to be on the server side separately from the code of the plugin? If so, I will copy this file to the plugin package - @rodedzats

**Comment by rodedzats** [comment]
@mdoron I think you can just import it

**Comment by mdoron** [comment]
I've managed to extract the line number of the first file and put there a comment, I'm working on actually getting the file path and then it will be all done. #72

**Comment by mdoron** [comment]
I put this on-hold until I finish #72

**Comment by yonzarecki** [comment]
As you're done with #72, I'm removing the on-hold label

**Comment by mdoron** [comment]
Closing this since it's not clear, will open a new one when needed
