### ISSUE TITLE
Research Bootstrap Platform

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#79]
As mentioned in #77, a platform shift planned for this semester is moving the website front-end to the [bootstrap](http://getbootstrap.com/) platform.

This week we plan to research this platform by reading it's tutorials and guides, and assess how long it will take us to make this shift, and see what other new ideas we can do with it.

**Comment by AdiOmari** [comment]
@yonzarecki  During the reading, please post a summary for this subject that includes a brief explanation of every major thing we should know with references to the full tutorials.

**Comment by yonzarecki** [comment]
Alright, here are some link I've found yesterday, I'll post a more complete tutorial when I'm done processing everything.

- [ ] [Include bootstrap into an eclipse project](https://www.texniq.de/en/web-engineering-i/create-first-bootstrap-project).
- [ ] [Add bootstrap to a spring boot application](https://springframework.guru/spring-boot-web-application-part-4-spring-mvc/) (the framework we're working with).
- [ ] [Official bootstrap getting started](http://getbootstrap.com/getting-started/)

Right now I'm looking into how to install bootstrap and have a 'hello world' going, this oracle [guide](http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/basic_app_embedded_tomcat/basic_app-tomcat-embedded.html) talks about it and also the previous links, so it won't be much of an issue.

**Comment by yonzarecki** [comment]
You find my and @rodedzats's minimal bootstrap example at this repo [bootstrap-bq-example](https://github.com/rodedzats/bootstrap-bq-example/tree/master).

**Comment by yonzarecki** [comment]
Right now I'm following [this](https://www.taniarascia.com/what-is-bootstrap-and-how-do-i-use-it/) example which creates a simple bootstrap page.

**Comment by yonzarecki** [comment]
Done with research @rodedzats

**Comment by yonzarecki** [comment]
As a summary to this research, I would like to point out there are a very vast amount of resources on bootstrap, and a large number of examples. It seems bootstrap indeed has a very large community.
In order to progress further we'll need to find and incorporate the relevant examples into our own code base. 
Finding each feature's example and incorporate it will take some time, but will look great :smile:
