### ISSUE TITLE
Integrate our website with bootstrap

### ISSUE THREAD

**Issue by rodedzats** [TechnionYP5777/Bugquery#81]
Following our UI meeting, we should integerate our current website with the bootstrap platform.

**Comment by yonzarecki** [comment]
We're facing some issues actually using bootstrap in our project.
We're working on it. @rodedzats

**Comment by yonzarecki** [comment]
Changing the milestone to Spring 1, as after our meeting with yossi were not sure we'll continue in this direction as of this week.

**Comment by yonzarecki** [comment]
I'd say we're ready this week to include the initial support for bootstrap, if everyone is busy I can take care of it.

**Comment by yosefraisman** [comment]
I completed all the work for this issue, using an older version of the site (since `spring-boot:run` no longer works for me? @AmitOhayon). I'd like someone to please make sure everything runs smoothly with the current version too.

![](https://media.giphy.com/media/fFujvanYFtEis/giphy.gif?response_id=591f3ef737277891712e0f56)

**Comment by yosefraisman** [comment]
I'll post some screenshots later.

**Comment by yosefraisman** [comment]
Managed to test with the current version myself. As promised, here are some
### Screenshots
#### Home
![localhost-8080-](https://cloud.githubusercontent.com/assets/16455692/26275253/1e3eb026-3d65-11e7-88e3-01a75f5c6d41.png)
#### Submit
![localhost-8080-submit](https://cloud.githubusercontent.com/assets/16455692/26275254/23635af2-3d65-11e7-956c-a3d5889aa9a8.png)
#### Results
![localhost-8080-stacks-1](https://cloud.githubusercontent.com/assets/16455692/26275258/3ceaf908-3d65-11e7-9aaa-348da2fad598.png)
#### Results - Extended Original Question
![localhost-8080-stacks-1 1](https://cloud.githubusercontent.com/assets/16455692/26275285/93e5497a-3d65-11e7-8a47-4902669155bc.png)
#### Error Page
![localhost-8080-stacks-42](https://cloud.githubusercontent.com/assets/16455692/26275290/a54d6f62-3d65-11e7-9cdb-72ec22f28d17.png)
