### ISSUE TITLE
Code coverage automation

### ISSUE THREAD

**Issue by ZivIzhar** [TechnionYP5777/Bugquery#85]
Add code coverage checks automation.

**Comment by ZivIzhar** [comment]
You can see the codecov summary here: https://codecov.io/gh/TechnionYP5777/Bugquery
It only includes the project ServerSide atm!

**Comment by yonzarecki** [comment]
Changing the milestone to Week 6.
#93

**Comment by ZivIzhar** [comment]
When the plugin will be tested, we'll include it in the codecov automation.
