### ISSUE TITLE
Add me to your telegram group

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Bugquery#87]
Let's fix a meeting this week.

**Comment by mdoron** [comment]
Although I'm on a week off, I couldn't stand silent in light of the drastic logistic changes in our team. The BugQuery team welcomes @yossigil as our new instructor, and in the very same beat are sorry for the leaving of @AdiOmari.
@yosefraisman @AmitOhayon @tonylekhtman @rodedzats @yonilx
