### ISSUE TITLE
Break down to separate issues, referencing this if necessary, and close.

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#90]
During our presentation today Yossi suggested some improvements, all of them are listed here :

1. Detect ab* pattern traces and change similarity code to reflect that: Issue already open at #89 .
2. Remove OK button from the plugin (will make experience more fluent and instant). #95 
3. **Technical challenge** - Change the JVM and hook the exception writing component to automatically call the BugQuery methods and send the exception to the server. (Assuming I understood this right) #96
At the end we should have our own JVM distribution with BugQuery built in.
4. Build thinking groups for new directions in the project:

   - Should we use a different programming language such as python when parsing the web (for new stack traces) ? #98 
   - Should we also implement an IntelliJ plugin ? #97 
   - Should we add auto-suggestion at the moment an exception is detected (without the user clicking the button) ? #99 

We should talk about these suggestion, incorporate the ones that fit our time and will contribute to our project the most.

**Comment by mdoron** [comment]
> Build thinking groups for new directions in the project:
> 
> Should we use a different programming language such as python when parsing the web (for new stack traces) ?
> Should we also implement an IntelliJ plugin ?
> Should we add auto-suggestion at the moment an exception is detected (without the user clicking the button) ?

This is not a proper issue. I think the current issue can be closed @yonilx.

**Comment by yossigil** [comment]
So close it

**Comment by yonzarecki** [comment]
I haven't finished opening all the issues yet :/
That's why this issue is still open.

**Comment by yonzarecki** [comment]
OK now I'm finished, closing
