### ISSUE TITLE
Fix Breakage from Commit

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Bugquery#92]
e0ac8a221561ea011d4f6a5b8a99c9efef1e5685 by @yossigil breaks our automatic testing. Find out why and change the code accordingly.

**Comment by AmitOhayon** [comment]
The class com.bugquery.serverside.entities.PostStub is in src instead of test. Yossi made a comment about it and imported the relevant test which made the tests fail.
(Sorry for taking over Ziv, got email notification and didn't see it is assigned to you)

**Comment by ZivIzhar** [comment]
😭

**Comment by yossigil** [comment]
:+1:
