### ISSUE TITLE
Clean up server code

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#94]
Remove todos and clean up code.

**Comment by yonzarecki** [comment]
Nice job @rodedzats, seems like you finished cleaning up your TODOs.

**Comment by yonzarecki** [comment]
Remaining TODOs in the server's code, I'm tagging whoever is written as this file's author to hopefully fix this.

- [ ] DBUpdater.java - @ZivIzhar 

- [ ] StackSearch.java - @AmitOhayon 

- [ ] StackOverflowPost.java - @ZivIzhar 

- [ ] DataBaseSomethingRenameMe.java - @tonylekhtman

**Comment by tonylekhtman** [comment]
StackOverflowPost is also under my work

**Comment by yonzarecki** [comment]
Blocked by #76 for StackOverflowPost.java and DataBaseSomethingRenameMe.java

**Comment by yonzarecki** [comment]
Any progress on StackOverflowPost.java and DataBaseSomethingRenameMe.java TODOs ?

**Comment by tonylekhtman** [comment]
These classes are going to be deleted soon anyway. We are redesigning the DAL as discussed in #102 as suggested by the ideas of @AmitOhayon

**Comment by yonzarecki** [comment]
So i'll just close this issue if you guys are working on it.

**Comment by yonzarecki** [comment]
Closing as this seems to be under control in #102
