### ISSUE TITLE
Remove OK button from the plugin

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#95]
Remove OK button from the plugin, will make the experience more fluent. As discussed with Yossi.

**Comment by yossigil** [comment]
Philosophy is: suggest a solution, don't wait for the user to ask

**Comment by yonzarecki** [comment]
We decided to use the quick solution of using the working solution when working on Windows and retain the OK button when working on linux (as it is a technical challenge to implement it there)
