### ISSUE TITLE
Thinking group - Building an IntelliJ plugin

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#97]
In this thinking group we should discuss building an IntelliJ plugin for BugQuery.
We should check what are difficulties of building such a plugin, can we move some of our eclipse code, how much time will it take.

**Comment by AmitOhayon** [comment]
To use @yossigil's words, isn't it trying to adapt the plugin for them masses when there are no masses?
In my opinion this should be of lower priority since we have work to do on the core.

**Comment by mdoron** [comment]
@AmitOhayon I agree

**Comment by yonzarecki** [comment]
This isn't a critical issue I agree, I assigned it to Sprint 1 so the idea won't be forgotten not to press anyone to work on it ATM.
Maybe a better choice is to assign it to Sprint 2.
