### ISSUE TITLE
Thinking group - Should we add an auto-suggestion when an exception is detected ?

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#99]
Should we automatically call BugQuery without asking the user, hopefully making the process much faster, but also add a lot of load to the server.
This thinking group will think about these questions.

**Comment by mdoron** [comment]
if there is a possibility to run in a "BugQuery mode", just like a debugging mode, I think this may be a good idea.

**Comment by mdoron** [comment]
@yosefraisman what are your thoughts toward this issue?

**Comment by yosefraisman** [comment]
I think we should prompt users before shipping their outputs away to an online service, unless they initiated a query process consciously (clicked a button in the stack trace console, ran their program in our launch configuration, etc.).
I'd also like to point out that "running in BugQuery Mode" is what we used to refer to as launch configuration, which we decided was too much of a hassle to implement.

**Comment by yonzarecki** [comment]
I agree with you Yosef, and if you guys think this suggestion will probably not happen just close this issue.
